## Look at the file report and also check md5sums in nanopore directory

In [1]:
import polars as pl

In [2]:
ls *.tsv

filereport_read_run_PRJEB88111-md5.tsv

In [3]:
runs_df = pl.read_csv('filereport_read_run_PRJEB88111-md5.tsv', separator='\t')

In [4]:
runs_df

shape: (108, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ run_acces ┆ study_acc ┆ secondary ┆ sample_ac ┆ … ┆ submitted ┆ submitted ┆ broker_na ┆ sample_t │
│ sion      ┆ ession    ┆ _study_ac ┆ cession   ┆   ┆ _bytes    ┆ _ftp      ┆ me        ┆ itle     │
│ ---       ┆ ---       ┆ cession   ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ i64       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ERR159098 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 85392745  ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2025 │
│ 55        ┆ 1         ┆           ┆ 77475     ┆   ┆           ┆ bi.ac.uk/ ┆           ┆ _1036890 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _101_MG_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ LVK_76…  │
│ ERR159098 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 132755280 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2025 │
│ 58        ┆ 1         ┆           ┆ 77463     ┆   ┆           ┆ bi.ac.uk/ ┆           ┆ _1036900 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _101_MG_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ LVK_10…  │
│ ERR159098 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 197537363 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2025 │
│ 74        ┆ 1         ┆           ┆ 77467     ┆   ┆           ┆ bi.ac.uk/ ┆           ┆ _1036899 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _101_MG_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ LVK_10…  │
│ ERR159098 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 134810182 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2025 │
│ 84        ┆ 1         ┆           ┆ 77465     ┆   ┆           ┆ bi.ac.uk/ ┆           ┆ _1036893 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _101_MG_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ LVK_82…  │
│ ERR159098 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 134085368 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2025 │
│ 85        ┆ 1         ┆           ┆ 77458     ┆   ┆           ┆ bi.ac.uk/ ┆           ┆ _1036892 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _101_MG_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ LVK_80…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ERR159422 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 133965972 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2024 │
│ 35        ┆ 1         ┆           ┆ 81437     ┆   ┆ 0         ┆ bi.ac.uk/ ┆           ┆ _1035964 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _100_SI_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ LVK_10…  │
│ ERR159422 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 739999824 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2024 │
│ 38        ┆ 1         ┆           ┆ 81431     ┆   ┆           ┆ bi.ac.uk/ ┆           ┆ _1035958 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _100_SI_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ LVK_74…  │
│ ERR159422 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 133258269 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2024 │
│ 45        ┆ 1         ┆           ┆ 81430     ┆   ┆ 5         ┆ bi.ac.uk/ ┆           ┆ _1035957 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _100_SI_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ LVK_61…  │
│ ERR159422 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 932150995 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2024 │
│ 49        ┆ 1         ┆           ┆ 81459     ┆   ┆           ┆ bi.ac.uk/ ┆           ┆ _1035986 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _100_SI_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ CP_43C…  │
│ ERR159422 ┆ PRJEB8811 ┆ ERP171251 ┆ SAMEA1205 ┆ … ┆ 167803014 ┆ ftp.sra.e ┆ DTU-GE    ┆ DTU_2024 │
│ 55        ┆ 1         ┆           ┆ 81467     ┆   ┆ 6         ┆ bi.ac.uk/ ┆           ┆ _1035994 │
│           ┆           ┆           ┆           ┆   ┆           ┆ vol1/run/ ┆           ┆ _100_SI_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ ERR…      ┆           ┆ CP_78B…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
md5_table = runs_df.select(['fastq_md5', 'run_accession'])
md5_table.head(1)

shape: (1, 2)
┌─────────────────────────────────┬───────────────┐
│ fastq_md5                       ┆ run_accession │
│ ---                             ┆ ---           │
│ str                             ┆ str           │
╞═════════════════════════════════╪═══════════════╡
│ 7316c3227f49c8cdacbe32cd99a976… ┆ ERR15909855   │
└─────────────────────────────────┴───────────────┘

## Write out md5s per ENA file report

In [6]:
with open('ENA-fastq-md5sum.txt', 'wt') as fp:
    for row in md5_table.sort('run_accession').iter_rows(named=True):
        print(f"{row['fastq_md5']}  {row['run_accession']}.fastq.gz", file=fp)

## Read in actual md5 sums

calculated via `md5sum *.fastq.gz > fastq-md5sum.txt.new `

In [7]:
md5_xx = []
for row in open('fastq-md5sum.txt'):
    md5, filename = row.strip().split('  ')
    acc = filename.split('.')[0]
    md5_xx.append(dict(actual_md5=md5, run_accession=acc))

actual_md5_df = pl.DataFrame(md5_xx)
actual_md5_df

shape: (108, 2)
┌─────────────────────────────────┬───────────────┐
│ actual_md5                      ┆ run_accession │
│ ---                             ┆ ---           │
│ str                             ┆ str           │
╞═════════════════════════════════╪═══════════════╡
│ b4ddfda8dbc838af613bc54418a1e8… ┆ ERR15909852   │
│ 7537eb4d0aee1f48a412d9d6d961d9… ┆ ERR15909853   │
│ 7316c3227f49c8cdacbe32cd99a976… ┆ ERR15909855   │
│ 0bbf136640f3f82e845ac341873ee6… ┆ ERR15909856   │
│ 55a7e023591ff22ae51f9b373cd892… ┆ ERR15909857   │
│ …                               ┆ …             │
│ 83896f490d099605c5bdab4d573f2b… ┆ ERR15942238   │
│ 614c9802bd67237c3e0044201c1912… ┆ ERR15942241   │
│ 2319bf174ceb94aaec282c872c5830… ┆ ERR15942245   │
│ abc5be48ccbd4f3e05adc47a7bfd0f… ┆ ERR15942249   │
│ e8baea010525d953ba01febd8b918d… ┆ ERR15942255   │
└─────────────────────────────────┴───────────────┘

## Join actual with expected and compare

In [8]:
join_df = md5_table.join(actual_md5_df, how='left', on='run_accession').fill_null('xx')
join_df.head(1)

shape: (1, 3)
┌─────────────────────────────────┬───────────────┬─────────────────────────────────┐
│ fastq_md5                       ┆ run_accession ┆ actual_md5                      │
│ ---                             ┆ ---           ┆ ---                             │
│ str                             ┆ str           ┆ str                             │
╞═════════════════════════════════╪═══════════════╪═════════════════════════════════╡
│ 7316c3227f49c8cdacbe32cd99a976… ┆ ERR15909855   ┆ 7316c3227f49c8cdacbe32cd99a976… │
└─────────────────────────────────┴───────────────┴─────────────────────────────────┘

In [9]:
bad_acc = join_df.filter(pl.col('fastq_md5') != pl.col('actual_md5'))
bad_acc

shape: (0, 3)
┌───────────┬───────────────┬────────────┐
│ fastq_md5 ┆ run_accession ┆ actual_md5 │
│ ---       ┆ ---           ┆ ---        │
│ str       ┆ str           ┆ str        │
╞═══════════╪═══════════════╪════════════╡
└───────────┴───────────────┴────────────┘

In [10]:
## print out all the actually bad md5s

In [11]:
xx = [ f"{acc}.fastq.gz" for acc in bad_acc['run_accession'] ]

print(' '.join(xx))

In [12]:
len(actual_md5_df)

108

In [13]:
len(join_df)

108