In [1]:
import polars as pl
import screed

In [2]:
df = pl.read_csv('bac120_metadata_r226.tsv.gz', separator='\t', ignore_errors=True)

In [3]:
df.head(1).columns

['accession',
 'ambiguous_bases',
 'checkm2_completeness',
 'checkm2_contamination',
 'checkm2_model',
 'checkm_completeness',
 'checkm_contamination',
 'checkm_marker_count',
 'checkm_marker_lineage',
 'checkm_marker_set_count',
 'checkm_strain_heterogeneity',
 'coding_bases',
 'coding_density',
 'contig_count',
 'gc_count',
 'gc_percentage',
 'genome_size',
 'gtdb_genome_representative',
 'gtdb_representative',
 'gtdb_taxonomy',
 'gtdb_type_designation_ncbi_taxa',
 'gtdb_type_designation_ncbi_taxa_sources',
 'gtdb_type_species_of_genus',
 'l50_contigs',
 'l50_scaffolds',
 'longest_contig',
 'longest_scaffold',
 'lsu_23s_contig_len',
 'lsu_23s_count',
 'lsu_23s_length',
 'lsu_23s_query_id',
 'lsu_5s_contig_len',
 'lsu_5s_count',
 'lsu_5s_length',
 'lsu_5s_query_id',
 'lsu_silva_23s_blast_align_len',
 'lsu_silva_23s_blast_bitscore',
 'lsu_silva_23s_blast_evalue',
 'lsu_silva_23s_blast_perc_identity',
 'lsu_silva_23s_blast_subject_id',
 'lsu_silva_23s_taxonomy',
 'mean_contig_length',
 'mean_scaffold_length',
 'mimag_high_quality',
 'mimag_low_quality',
 'mimag_medium_quality',
 'n50_contigs',
 'n50_scaffolds',
 'ncbi_assembly_level',
 'ncbi_assembly_name',
 'ncbi_assembly_type',
 'ncbi_bioproject',
 'ncbi_biosample',
 'ncbi_contig_count',
 'ncbi_contig_n50',
 'ncbi_country',
 'ncbi_date',
 'ncbi_genbank_assembly_accession',
 'ncbi_genome_category',
 'ncbi_genome_representation',
 'ncbi_isolate',
 'ncbi_isolation_source',
 'ncbi_lat_lon',
 'ncbi_molecule_count',
 'ncbi_ncrna_count',
 'ncbi_organism_name',
 'ncbi_protein_count',
 'ncbi_refseq_category',
 'ncbi_rrna_count',
 'ncbi_scaffold_count',
 'ncbi_scaffold_l50',
 'ncbi_scaffold_n50',
 'ncbi_scaffold_n75',
 'ncbi_scaffold_n90',
 'ncbi_seq_rel_date',
 'ncbi_spanned_gaps',
 'ncbi_species_taxid',
 'ncbi_ssu_count',
 'ncbi_strain_identifiers',
 'ncbi_submitter',
 'ncbi_taxid',
 'ncbi_taxonomy',
 'ncbi_taxonomy_unfiltered',
 'ncbi_total_gap_length',
 'ncbi_total_length',
 'ncbi_translation_table',
 'ncbi_trna_count',
 'ncbi_type_material_designation',
 'ncbi_ungapped_length',
 'ncbi_unspanned_gaps',
 'ncbi_wgs_master',
 'protein_count',
 'scaffold_count',
 'ssu_contig_len',
 'ssu_count',
 'ssu_gg_blast_align_len',
 'ssu_gg_blast_bitscore',
 'ssu_gg_blast_evalue',
 'ssu_gg_blast_perc_identity',
 'ssu_gg_blast_subject_id',
 'ssu_gg_taxonomy',
 'ssu_length',
 'ssu_query_id',
 'ssu_silva_blast_align_len',
 'ssu_silva_blast_bitscore',
 'ssu_silva_blast_evalue',
 'ssu_silva_blast_perc_identity',
 'ssu_silva_blast_subject_id',
 'ssu_silva_taxonomy',
 'total_gap_length',
 'trna_aa_count',
 'trna_count',
 'trna_selenocysteine_count']

In [4]:
df.head(1).select([ 'gtdb_genome_representative',
 'gtdb_representative',
 'gtdb_taxonomy',])

shape: (1, 3)
┌────────────────────────────┬─────────────────────┬─────────────────────────────────┐
│ gtdb_genome_representative ┆ gtdb_representative ┆ gtdb_taxonomy                   │
│ ---                        ┆ ---                 ┆ ---                             │
│ str                        ┆ str                 ┆ str                             │
╞════════════════════════════╪═════════════════════╪═════════════════════════════════╡
│ RS_GCF_003697165.2         ┆ f                   ┆ d__Bacteria;p__Pseudomonadota;… │
└────────────────────────────┴─────────────────────┴─────────────────────────────────┘

In [5]:
df.head(1)['gtdb_taxonomy'].item()

'd__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Escherichia;s__Escherichia coli'

In [6]:
CORE_NAMES=set([ x.strip() for x in open('inputs.branchwater/names.list') ])

In [7]:
df2 = df.filter(
    (pl.col('gtdb_taxonomy').str.split(';').list.get(-1).is_in(CORE_NAMES)) &
    (pl.col('gtdb_representative') == 't')
)

In [8]:
df3 = df2.with_columns(
    acc=pl.col('gtdb_genome_representative').str.slice(3)
)
df3.write_csv('PRJEB88111.nanopore/reps/reps.csv')

In [9]:
print("\n".join(df3['acc']))

GCA_900546925.1
GCA_022774325.1
GCF_002251295.1
GCF_021531895.1
GCA_004557565.1
GCF_009695905.1
GCA_002320005.1
GCF_002706375.1
GCA_902472425.1
GCA_002299675.1
GCA_034089285.1
GCF_019052365.1
GCF_009696175.1
GCA_004552595.1
GCA_022785155.1
GCA_000434935.1

## build list of contigs per species

In [10]:
ls reps

ls: cannot access 'reps': No such file or directory

In [11]:
pwd

'/group/datalabgrp/ctbrown/2026-pancoding-core'

In [12]:
ls PRJEB88111.nanopore/reps/

GCA_000434935.1_genomic.fna.gz  GCF_002706375.1_genomic.fna.gz
GCA_002299675.1_genomic.fna.gz  GCF_009695905.1_genomic.fna.gz
GCA_002320005.1_genomic.fna.gz  GCF_009696175.1_genomic.fna.gz
GCA_004552595.1_genomic.fna.gz  GCF_019052365.1_genomic.fna.gz
GCA_004557565.1_genomic.fna.gz  GCF_021531895.1_genomic.fna.gz
GCA_022774325.1_genomic.fna.gz  all-core.fa
GCA_022785155.1_genomic.fna.gz  bams/
GCA_034089285.1_genomic.fna.gz  contigs_to_species.csv
GCA_900546925.1_genomic.fna.gz  list.txt
GCA_902472425.1_genomic.fna.gz  reps.csv
GCF_002251295.1_genomic.fna.gz

In [13]:
df3['acc']

shape: (16,)
Series: 'acc' [str]
[
	"GCA_900546925.1"
	"GCA_022774325.1"
	"GCF_002251295.1"
	"GCF_021531895.1"
	"GCA_004557565.1"
	…
	"GCF_019052365.1"
	"GCF_009696175.1"
	"GCA_004552595.1"
	"GCA_022785155.1"
	"GCA_000434935.1"
]

In [14]:
contig_xx = []
for row in df3.iter_rows(named=True):
    acc = row['acc']
    species = row['gtdb_taxonomy'].split(';')[-1]

    filename = f'PRJEB88111.nanopore/reps/{acc}_genomic.fna.gz'
    for record in screed.open(filename):
        contig_xx.append(dict(contig=record.name.split(' ')[0],
                              species=species,
                              acc=acc))

contig_df = pl.DataFrame(contig_xx)

In [15]:
contig_df

shape: (1_552, 3)
┌────────────────┬─────────────────────────────────┬─────────────────┐
│ contig         ┆ species                         ┆ acc             │
│ ---            ┆ ---                             ┆ ---             │
│ str            ┆ str                             ┆ str             │
╞════════════════╪═════════════════════════════════╪═════════════════╡
│ UREV01000001.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ UREV01000002.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ UREV01000003.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ UREV01000004.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ UREV01000005.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ …              ┆ …                               ┆ …               │
│ FR882205.1     ┆ s__Cryptobacteroides sp0004349… ┆ GCA_000434935.1 │
│ FR882206.1     ┆ s__Cryptobacteroides sp0004349… ┆ GCA_000434935.1 │
│ FR882207.1     ┆ s__Cryptobacteroides sp0004349… ┆ GCA_000434935.1 │
│ FR882208.1     ┆ s__Cryptobacteroides sp0004349… ┆ GCA_000434935.1 │
│ FR882209.1     ┆ s__Cryptobacteroides sp0004349… ┆ GCA_000434935.1 │
└────────────────┴─────────────────────────────────┴─────────────────┘

In [17]:
contig_df.write_csv('PRJEB88111.nanopore/reps/contigs_to_species.csv')