# Explore the 'other' category of branchwater matches

In [15]:
import polars as pl

In [19]:
# produced by branchwater-figure.ipynb
found_df = pl.read_csv('branchwater_8species_other.csv')

In [20]:
# get metadata, only compare WGS
metadata_df = (
    pl.scan_parquet("/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet")
    .filter(pl.col("acc") != "NP")
    .filter(pl.col("assay_type") == "WGS")
#    .select(["acc", "organism", "bioproject", "mbases", "host", "project_name"]) 
    .collect()
)
print(f"found metadata records for {len(metadata_df)} WGS metagenome data sets from the SRA")

found metadata records for 703916 WGS metagenome data sets from the SRA

In [21]:
found_df2 = found_df.join(metadata_df, on=['acc', 'bioproject', 'organism'], how='inner')

In [22]:
all_bioproject_sum_df = metadata_df.group_by('bioproject').agg(
    n_acc_total=pl.len(),
    orgs=pl.col('organism').unique(),
)

In [23]:
found_df2.group_by('bioproject').agg(
    n_acc_matched=pl.len(),
).join(all_bioproject_sum_df, on='bioproject', how='inner').sort('n_acc_matched').filter(pl.col('n_acc_matched') > 2)

shape: (10, 4)
┌──────────────┬───────────────┬─────────────┬─────────────────────────────────┐
│ bioproject   ┆ n_acc_matched ┆ n_acc_total ┆ orgs                            │
│ ---          ┆ ---           ┆ ---         ┆ ---                             │
│ str          ┆ u32           ┆ u32         ┆ list[str]                       │
╞══════════════╪═══════════════╪═════════════╪═════════════════════════════════╡
│ PRJNA1121201 ┆ 3             ┆ 97          ┆ ["bioreactor metagenome", "pig… │
│ PRJNA623064  ┆ 3             ┆ 84          ┆ ["dust metagenome"]             │
│ PRJNA684647  ┆ 3             ┆ 18          ┆ ["soil metagenome"]             │
│ PRJNA699174  ┆ 5             ┆ 24          ┆ ["air metagenome"]              │
│ PRJEB31650   ┆ 5             ┆ 567         ┆ ["pig gut metagenome", "wastew… │
│ PRJNA892010  ┆ 7             ┆ 27          ┆ ["compost metagenome"]          │
│ PRJNA526405  ┆ 8             ┆ 3598        ┆ ["pig gut metagenome", "synthe… │
│ PRJNA292471  ┆ 9             ┆ 87          ┆ ["bovine metagenome"]           │
│ PRJNA506496  ┆ 32            ┆ 39          ┆ ["fermentation metagenome"]     │
│ PRJEB34634   ┆ 166           ┆ 2076        ┆ ["sediment metagenome"]         │
└──────────────┴───────────────┴─────────────┴─────────────────────────────────┘

## Explore PRJNA892010, compost metagenome

Microbiome in swine manure composting Genome sequencing and assembly

https://www.sciencedirect.com/science/article/abs/pii/S0956053X2400059X uses this data but is maybe not the author?

In [35]:
found_df2.filter(pl.col('bioproject') == 'PRJNA892010')

shape: (7, 72)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR2201351 ┆ PRJNA89201 ┆ compost    ┆ 10    ┆ … ┆ 321357296 ┆ "2022-10- ┆ null      ┆ "31373652 │
│ 7          ┆ 0          ┆ metagenome ┆       ┆   ┆ 2         ┆ 22T15:39: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201351 ┆ PRJNA89201 ┆ compost    ┆ 9     ┆ … ┆ 395655131 ┆ "2022-10- ┆ null      ┆ "31373634 │
│ 1          ┆ 0          ┆ metagenome ┆       ┆   ┆ 8         ┆ 22T15:46: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201351 ┆ PRJNA89201 ┆ compost    ┆ 10    ┆ … ┆ 344833488 ┆ "2022-10- ┆ null      ┆ "31373633 │
│ 2          ┆ 0          ┆ metagenome ┆       ┆   ┆ 5         ┆ 22T15:56: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201352 ┆ PRJNA89201 ┆ compost    ┆ 8     ┆ … ┆ 342662878 ┆ "2022-10- ┆ null      ┆ "31373644 │
│ 6          ┆ 0          ┆ metagenome ┆       ┆   ┆ 7         ┆ 22T15:38: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201351 ┆ PRJNA89201 ┆ compost    ┆ 13    ┆ … ┆ 324825042 ┆ "2022-10- ┆ null      ┆ "31373651 │
│ 8          ┆ 0          ┆ metagenome ┆       ┆   ┆ 1         ┆ 22T16:03: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201352 ┆ PRJNA89201 ┆ compost    ┆ 8     ┆ … ┆ 322982314 ┆ "2022-10- ┆ null      ┆ "31373643 │
│ 7          ┆ 0          ┆ metagenome ┆       ┆   ┆ 8         ┆ 22T15:41: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201351 ┆ PRJNA89201 ┆ compost    ┆ 8     ┆ … ┆ 326762569 ┆ "2022-10- ┆ null      ┆ "31373635 │
│ 0          ┆ 0          ┆ metagenome ┆       ┆   ┆ 6         ┆ 22T15:58: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA292471, bovine metagenome

The purpose of this study was to describe the beef production metagenome and resistome as pens of cattle moved through the feeding period, slaughter and fabrication. Longitudinal, pooled samples from 8 pens of cattle were collected at arrival in and exit from 4 feedlots (feces, soil and drinking water); from the transport trucks used to transport cattle to 2 abattoirs (sponges); from the holding pens at 2 abattoirs (feces and drinking water); and from fabrication belts (sponges) and trimmings (rinsates) at the end of the fabrication process.

some feces_exit and some feces_holding.

In [34]:
found_df2.filter(pl.col('bioproject') == 'PRJNA292471')

shape: (9, 72)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR3053217 ┆ PRJNA29247 ┆ bovine     ┆ 8     ┆ … ┆ 539583263 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T17:21: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053209 ┆ PRJNA29247 ┆ bovine     ┆ 10    ┆ … ┆ 779322913 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T18:23: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053212 ┆ PRJNA29247 ┆ bovine     ┆ 9     ┆ … ┆ 800993482 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T18:17: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053216 ┆ PRJNA29247 ┆ bovine     ┆ 10    ┆ … ┆ 805977217 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T14:20: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053207 ┆ PRJNA29247 ┆ bovine     ┆ 8     ┆ … ┆ 769428565 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T14:21: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053211 ┆ PRJNA29247 ┆ bovine     ┆ 9     ┆ … ┆ 869863678 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T18:24: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053210 ┆ PRJNA29247 ┆ bovine     ┆ 9     ┆ … ┆ 965925569 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T18:25: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053208 ┆ PRJNA29247 ┆ bovine     ┆ 10    ┆ … ┆ 945478112 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T18:23: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053215 ┆ PRJNA29247 ┆ bovine     ┆ 9     ┆ … ┆ 746591220 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T17:22: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA506496, fermentation metagenome

This study aims to investigate what microbes capable of utilizing plant cell wall polysaccharides and their functions. The submitted metagenomic sequences include three in vitro fermentation experiments (P1, P2 & H). Of P1, wheat arabinoxylan and rye arabinoxylan were fermented for up to 48 h with a porcine faecal inoculum. Of P2, wheat arabinoxylan and tamarind galactoxyloglucan were fermented for up 72 h with a porcine fecal inoculum. For H, wheat arabinoxylan and tamarind galactoxyloglucan were fermented for up 48 h with a human fecal inoculum. The polysaccharides were the only carbon source in the medium for microbial growth.

all 32 pig (P1 and P2) were found; all 7 H not.

In [27]:
found_df2.filter(pl.col('bioproject') == 'PRJNA506496')

shape: (32, 72)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR8242829 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 595478324 ┆ "2018-11- ┆ null      ┆ "10461889 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:39: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242822 ┆ PRJNA50649 ┆ fermentati ┆ 10    ┆ … ┆ 484418357 ┆ "2018-11- ┆ null      ┆ "10461870 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:37: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242852 ┆ PRJNA50649 ┆ fermentati ┆ 12    ┆ … ┆ 612632202 ┆ "2018-11- ┆ null      ┆ "10461884 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:42: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242826 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 628406126 ┆ "2018-11- ┆ null      ┆ "10461874 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:39: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242827 ┆ PRJNA50649 ┆ fermentati ┆ 14    ┆ … ┆ 489367506 ┆ "2018-11- ┆ null      ┆ "10461873 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:39: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR8242824 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 564996261 ┆ "2018-11- ┆ null      ┆ "10461872 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:37: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242828 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 623216576 ┆ "2018-11- ┆ null      ┆ "10461890 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:39: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242856 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 522624631 ┆ "2018-11- ┆ null      ┆ "10461880 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:41: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242847 ┆ PRJNA50649 ┆ fermentati ┆ 12    ┆ … ┆ 603830837 ┆ "2018-11- ┆ null      ┆ "10461885 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:41: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242855 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 497984275 ┆ "2018-11- ┆ null      ┆ "10461879 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:41: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

In [30]:
found_df2.filter(pl.col('bioproject') == 'PRJNA506496').with_columns(
    exp=pl.col('library_name').str.split('_').list.get(0)
).sort('exp')['exp'].unique()

shape: (2,)
Series: 'exp' [str]
[
	"P2"
	"P1"
]

In [32]:
metadata_df.filter(pl.col('bioproject') == 'PRJNA506496').with_columns(
    exp=pl.col('library_name').str.split('_').list.get(0)
)['exp'].value_counts()

shape: (3, 2)
┌─────┬───────┐
│ exp ┆ count │
│ --- ┆ ---   │
│ str ┆ u32   │
╞═════╪═══════╡
│ H   ┆ 7     │
│ P2  ┆ 19    │
│ P1  ┆ 13    │
└─────┴───────┘

## Explore PRJEB34634, sediment metagenome

We do not fully understand how important types (species) of bacteria and packages of genetic material (genes) coding for antibiotic resistance move between humans, animals and the environment, or where, how and why antibiotic resistance emerges. This study aims to look in detail at the genetic level at bacteria in farm animals, human/animal sewage, sewage treatment works and rivers, to work out the complex network of transmission of important antibiotic-resistant bacteria and antibiotic resistance genes. We will use this information to work out how best to slow down the spread of antibiotic resistance between humans, livestock and the environment.

Seems like no pub? No metadata available.

In [26]:
found_df2.filter(pl.col('bioproject') == 'PRJEB34634').head(1)['center_name'].item()

'CENTRE FOR ECOLOGY AND HYDROLOGY'

In [25]:
found_df2.filter(pl.col('bioproject') == 'PRJEB34634')

shape: (166, 72)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ERR3574843 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 631562187 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T15:11: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574765 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 695261972 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T14:09: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574468 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 836986557 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:47: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574662 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 882060742 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T15:33: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574466 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 833371811 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:46: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ ERR3574903 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 606395164 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T17:18: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574838 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 632616070 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T15:15: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574488 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ 742896474 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:42: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574477 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ 704018595 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:43: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574486 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ 796950279 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:48: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘