# Overall dataset summary information

In [1]:
import polars as pl

## Load the accessions of the 3216

In [2]:
names_3216_df = (pl.read_csv('../3216.manifest.csv')
                 .with_columns(acc=pl.col('name'))
                 ['acc'].unique().to_frame()
                )
assert len(names_3216_df) == 3216, len(names_3216_df)

## Get metadata

In [3]:
metadata_df = (
    pl.scan_parquet("/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet")
    .filter(pl.col("acc") != "NP")
    .filter(pl.col("assay_type") == "WGS")
#    .select(["acc", "organism", "bioproject", "mbases", "host", "project_name"]) 
    .collect()
)
print(f"found metadata records for {len(metadata_df)} WGS metagenome data sets from the SRA")

found metadata records for 703916 WGS metagenome data sets from the SRA

## Join!

In [5]:
join_df = names_3216_df.join(metadata_df, on='acc', how='inner')
assert len(join_df) == 3216

In [9]:
join_df['bioproject'].value_counts().sort('count', descending=True)

shape: (26, 2)
┌─────────────┬───────┐
│ bioproject  ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ PRJNA526405 ┆ 2103  │
│ PRJEB11755  ┆ 295   │
│ PRJEB31650  ┆ 245   │
│ PRJNA788462 ┆ 186   │
│ PRJEB50613  ┆ 62    │
│ …           ┆ …     │
│ PRJNA601162 ┆ 4     │
│ PRJNA633385 ┆ 4     │
│ PRJNA389749 ┆ 3     │
│ PRJNA857725 ┆ 2     │
│ PRJNA293646 ┆ 2     │
└─────────────┴───────┘

In [12]:
join_df['biosample'].value_counts().sort('count', descending=True)

shape: (1_949, 2)
┌──────────────┬───────┐
│ biosample    ┆ count │
│ ---          ┆ ---   │
│ str          ┆ u32   │
╞══════════════╪═══════╡
│ SAMN06318508 ┆ 8     │
│ SAMN11098522 ┆ 5     │
│ SAMN11098442 ┆ 5     │
│ SAMN11098454 ┆ 5     │
│ SAMN11098427 ┆ 5     │
│ …            ┆ …     │
│ SAMEA3663185 ┆ 1     │
│ SAMN12867443 ┆ 1     │
│ SAMN11039342 ┆ 1     │
│ SAMN11097714 ┆ 1     │
│ SAMN11098202 ┆ 1     │
└──────────────┴───────┘

In [13]:
join_df['geo_loc_name_country_continent_calc'].value_counts().sort('count', descending=True)

shape: (5, 2)
┌─────────────────────────────────┬───────┐
│ geo_loc_name_country_continent… ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Oceania                         ┆ 2103  │
│ Europe                          ┆ 631   │
│ North America                   ┆ 250   │
│ Asia                            ┆ 208   │
│ uncalculated                    ┆ 24    │
└─────────────────────────────────┴───────┘

In [14]:
join_df['platform'].value_counts().sort('count', descending=True)

shape: (1, 2)
┌──────────┬───────┐
│ platform ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ ILLUMINA ┆ 3216  │
└──────────┴───────┘

In [15]:
join_df['organism'].value_counts().sort('count', descending=True)

shape: (1, 2)
┌────────────────────┬───────┐
│ organism           ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ pig gut metagenome ┆ 3216  │
└────────────────────┴───────┘

In [16]:
join_df['mbases'].describe()

shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ value       │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 3216.0      │
│ null_count ┆ 0.0         │
│ mean       ┆ 5123.719527 │
│ std        ┆ 5138.40469  │
│ min        ┆ 1001.0      │
│ 25%        ┆ 1420.0      │
│ 50%        ┆ 4023.0      │
│ 75%        ┆ 6115.0      │
│ max        ┆ 49918.0     │
└────────────┴─────────────┘

In [11]:
join_df

shape: (3_216, 67)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ acc       ┆ sample_na ┆ sample_na ┆ assay_typ ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_ │
│ ---       ┆ me        ┆ me_sam    ┆ e         ┆   ┆ ---       ┆ create_da ┆ version   ┆ search   │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---      │
│           ┆ str       ┆ list[str] ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR111254 ┆ Fe24/1420 ┆ []        ┆ WGS       ┆ … ┆ 416591685 ┆ "2020-02- ┆ null      ┆ "1109829 │
│ 86        ┆ 8         ┆           ┆           ┆   ┆           ┆ 20T21:25: ┆           ┆ 8"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ ERR113538 ┆ SAMEA3663 ┆ ["BHZ-7B" ┆ WGS       ┆ … ┆ 460732824 ┆ "2016-01- ┆ null      ┆ "308698" │
│ 7         ┆ 214       ┆ ]         ┆           ┆   ┆ 6         ┆ 13T01:23: ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ SRR111260 ┆ Fe24/1420 ┆ []        ┆ WGS       ┆ … ┆ 424454702 ┆ "2020-02- ┆ null      ┆ "1109829 │
│ 80        ┆ 8         ┆           ┆           ┆   ┆           ┆ 20T22:03: ┆           ┆ 8"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ SRR111247 ┆ Fe21/2979 ┆ []        ┆ WGS       ┆ … ┆ 394096836 ┆ "2020-02- ┆ null      ┆ "1109825 │
│ 55        ┆ 6         ┆           ┆           ┆   ┆           ┆ 20T20:34: ┆           ┆ 0"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ SRR127998 ┆ PI_5      ┆ []        ┆ WGS       ┆ … ┆ 236836219 ┆ "2020-10- ┆ null      ┆ "1640209 │
│ 33        ┆           ┆           ┆           ┆   ┆ 8         ┆ 09T06:17: ┆           ┆ 5"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SRR111249 ┆ Fe7/14183 ┆ []        ┆ WGS       ┆ … ┆ 333202038 ┆ "2020-02- ┆ null      ┆ "1109795 │
│ 12        ┆           ┆           ┆           ┆   ┆           ┆ 20T20:45: ┆           ┆ 0"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ SRR896014 ┆ Ma8/14306 ┆ []        ┆ WGS       ┆ … ┆ 173025457 ┆ "2019-04- ┆ null      ┆ "1109845 │
│ 3         ┆           ┆           ┆           ┆   ┆ 3         ┆ 26T03:09: ┆           ┆ 9"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ SRR111254 ┆ Fe28/2970 ┆ []        ┆ WGS       ┆ … ┆ 385233982 ┆ "2020-02- ┆ null      ┆ "1109831 │
│ 72        ┆ 5         ┆           ┆           ┆   ┆           ┆ 20T21:17: ┆           ┆ 0"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ SRR111838 ┆ Ma9/14208 ┆ []        ┆ WGS       ┆ … ┆ 457484814 ┆ "2020-02- ┆ null      ┆ "1109847 │
│ 01        ┆           ┆           ┆           ┆   ┆           ┆ 26T03:30: ┆           ┆ 8"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
│ SRR111852 ┆ Ma7/14186 ┆ []        ┆ WGS       ┆ … ┆ 587822447 ┆ "2020-02- ┆ null      ┆ "1109844 │
│ 54        ┆           ┆           ┆           ┆   ┆ 8         ┆ 27T08:54: ┆           ┆ 4"       │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘