# Look at mapping breadth and depth of 100 x metagenomes to singleclust genes

...find more candidate genes

In [1]:
import polars as pl
import glob
import os
import screed
import csv
import screed

In [4]:
seq_to_species_df = (
    pl.read_csv('../outputs.mapping/cds-min50-singleclust/species_to_genes.csv')
    .rename({ 'ident': 'gene' })
    .select(['gene', 'species'])
)
seq_to_species_df

shape: (9_184, 2)
┌───────────────────────────────┬────────────────────────────┐
│ gene                          ┆ species                    │
│ ---                           ┆ ---                        │
│ str                           ┆ str                        │
╞═══════════════════════════════╪════════════════════════════╡
│ AtH2023_ERR1135319_MAG02_1_7  ┆ s__Bariatricus sp004560705 │
│ AtH2023_ERR1135319_MAG02_1_10 ┆ s__Bariatricus sp004560705 │
│ AtH2023_ERR1135319_MAG02_1_13 ┆ s__Bariatricus sp004560705 │
│ AtH2023_ERR1135319_MAG02_1_23 ┆ s__Bariatricus sp004560705 │
│ AtH2023_ERR1135319_MAG02_1_27 ┆ s__Bariatricus sp004560705 │
│ …                             ┆ …                          │
│ JALFGL010000073.1_2           ┆ s__UBA2868 sp004552595     │
│ CAMTHS010000005.1_1           ┆ s__UBA2868 sp004552595     │
│ CAMTHS010000062.1_11          ┆ s__UBA2868 sp004552595     │
│ CAMTHS010000104.1_1           ┆ s__UBA2868 sp004552595     │
│ CALZLM010000032.1_8           ┆ s__UBA2868 sp004552595     │
└───────────────────────────────┴────────────────────────────┘

In [5]:
seq_to_species_df.group_by('species').agg(pl.len()).sort('len')

shape: (16, 2)
┌─────────────────────────────────┬──────┐
│ species                         ┆ len  │
│ ---                             ┆ ---  │
│ str                             ┆ u32  │
╞═════════════════════════════════╪══════╡
│ s__JAFBIX01 sp021531895         ┆ 1    │
│ s__Floccifex porci              ┆ 17   │
│ s__Mogibacterium_A kristiansen… ┆ 21   │
│ s__Fimisoma sp002320005         ┆ 40   │
│ s__Lactobacillus amylovorus     ┆ 182  │
│ …                               ┆ …    │
│ s__Ornithospirochaeta sp022785… ┆ 770  │
│ s__Prevotella sp000434975       ┆ 851  │
│ s__Cryptobacteroides sp9005469… ┆ 928  │
│ s__Prevotella sp002251295       ┆ 935  │
│ s__Sodaliphilus sp004557565     ┆ 2197 │
└─────────────────────────────────┴──────┘

## Read in summarized metag x species singleclust depth reports

This file contains depth-of-mapping information for all our genes.

In [11]:
depth_df = (
    pl.read_csv('../outputs.mapping/rand100-cds3.min50.depth.csv')
    .join(seq_to_species_df, on=['gene'])
)

In [12]:
depth_df

shape: (918_400, 8)
┌─────────────┬─────────────────┬──────┬──────┬──────────┬───────────┬───────────┬─────────────────┐
│ metag       ┆ gene            ┆ len  ┆ hits ┆ breadth  ┆ depth_all ┆ depth_cov ┆ species         │
│ ---         ┆ ---             ┆ ---  ┆ ---  ┆ ---      ┆ ---       ┆ ---       ┆ ---             │
│ str         ┆ str             ┆ i64  ┆ i64  ┆ f64      ┆ f64       ┆ f64       ┆ str             │
╞═════════════╪═════════════════╪══════╪══════╪══════════╪═══════════╪═══════════╪═════════════════╡
│ ERR3211766  ┆ AtH2023_SRR5976 ┆ 843  ┆ 843  ┆ 1.0      ┆ 9.85172   ┆ 9.85172   ┆ s__Prevotella   │
│             ┆ 187_MAG13_142_1 ┆      ┆      ┆          ┆           ┆           ┆ sp002251295     │
│ ERR3211766  ┆ JAJXEN010000047 ┆ 2916 ┆ 735  ┆ 0.252058 ┆ 0.363169  ┆ 1.440816  ┆ s__Prevotella   │
│             ┆ .1_8            ┆      ┆      ┆          ┆           ┆           ┆ sp000434975     │
│ ERR3211766  ┆ AtH2023_SRR8960 ┆ 567  ┆ 0    ┆ 0.0      ┆ 0.0       ┆ NaN       ┆ s__Colivicinus  │
│             ┆ 514_MAG08_242_7 ┆      ┆      ┆          ┆           ┆           ┆ sp002299675     │
│ ERR3211766  ┆ JAQYGO010000082 ┆ 1488 ┆ 302  ┆ 0.202957 ┆ 0.202957  ┆ 1.0       ┆ s__UBA2868      │
│             ┆ .1_2            ┆      ┆      ┆          ┆           ┆           ┆ sp004552595     │
│ ERR3211766  ┆ AtH2023_SRR5241 ┆ 2151 ┆ 2151 ┆ 1.0      ┆ 15.751278 ┆ 15.751278 ┆ s__Sodaliphilus │
│             ┆ 533_MAG03_126_2 ┆      ┆      ┆          ┆           ┆           ┆ sp004557565     │
│ …           ┆ …               ┆ …    ┆ …    ┆ …        ┆ …         ┆ …         ┆ …               │
│ SRR11125751 ┆ AtH2023_SRR8960 ┆ 4413 ┆ 3820 ┆ 0.865624 ┆ 2.273057  ┆ 2.625916  ┆ s__Colivicinus  │
│             ┆ 514_MAG08_157_1 ┆      ┆      ┆          ┆           ┆           ┆ sp002299675     │
│             ┆ …               ┆      ┆      ┆          ┆           ┆           ┆                 │
│ SRR11125751 ┆ CAVEFX010000252 ┆ 1239 ┆ 1171 ┆ 0.945117 ┆ 4.621469  ┆ 4.889838  ┆ s__Sodaliphilus │
│             ┆ .1_11           ┆      ┆      ┆          ┆           ┆           ┆ sp004557565     │
│ SRR11125751 ┆ JAHAYU010000085 ┆ 2349 ┆ 2255 ┆ 0.959983 ┆ 2.862069  ┆ 2.981375  ┆ s__Cryptobacter │
│             ┆ .1_10           ┆      ┆      ┆          ┆           ┆           ┆ oides           │
│             ┆                 ┆      ┆      ┆          ┆           ┆           ┆ sp9005469…      │
│ SRR11125751 ┆ AtH2023_SRR1436 ┆ 1311 ┆ 0    ┆ 0.0      ┆ 0.0       ┆ NaN       ┆ s__Cryptobacter │
│             ┆ 9225_MAG28_6_13 ┆      ┆      ┆          ┆           ┆           ┆ oides           │
│             ┆                 ┆      ┆      ┆          ┆           ┆           ┆ sp0004349…      │
│ SRR11125751 ┆ AtH2023_ERR3211 ┆ 3405 ┆ 3405 ┆ 1.0      ┆ 15.038767 ┆ 15.038767 ┆ s__Sodaliphilus │
│             ┆ 826_MAG3_57_1   ┆      ┆      ┆          ┆           ┆           ┆ sp004557565     │
└─────────────┴─────────────────┴──────┴──────┴──────────┴───────────┴───────────┴─────────────────┘

In [13]:
depth_df.filter(pl.col('depth_all').is_not_nan()).sort(by='depth_all', descending=True).filter(pl.col('depth_all') > 0.0)

shape: (728_563, 8)
┌─────────────┬──────────────┬──────┬──────┬──────────┬──────────────┬──────────────┬──────────────┐
│ metag       ┆ gene         ┆ len  ┆ hits ┆ breadth  ┆ depth_all    ┆ depth_cov    ┆ species      │
│ ---         ┆ ---          ┆ ---  ┆ ---  ┆ ---      ┆ ---          ┆ ---          ┆ ---          │
│ str         ┆ str          ┆ i64  ┆ i64  ┆ f64      ┆ f64          ┆ f64          ┆ str          │
╞═════════════╪══════════════╪══════╪══════╪══════════╪══════════════╪══════════════╪══════════════╡
│ SRR14369134 ┆ SFFG01000401 ┆ 702  ┆ 702  ┆ 1.0      ┆ 19357.985755 ┆ 19357.985755 ┆ s__Sodaliphi │
│             ┆ .1_1         ┆      ┆      ┆          ┆              ┆              ┆ lus          │
│             ┆              ┆      ┆      ┆          ┆              ┆              ┆ sp004557565  │
│ SRR17241521 ┆ AtH2023_SRR1 ┆ 324  ┆ 324  ┆ 1.0      ┆ 16832.611111 ┆ 16832.611111 ┆ s__Lactobaci │
│             ┆ 1183406_MAG1 ┆      ┆      ┆          ┆              ┆              ┆ llus         │
│             ┆ _196_4…      ┆      ┆      ┆          ┆              ┆              ┆ amylovorus   │
│ SRR11489750 ┆ SFFG01000401 ┆ 702  ┆ 702  ┆ 1.0      ┆ 15167.830484 ┆ 15167.830484 ┆ s__Sodaliphi │
│             ┆ .1_1         ┆      ┆      ┆          ┆              ┆              ┆ lus          │
│             ┆              ┆      ┆      ┆          ┆              ┆              ┆ sp004557565  │
│ SRR10209683 ┆ AtH2023_SRR8 ┆ 375  ┆ 375  ┆ 1.0      ┆ 15122.426667 ┆ 15122.426667 ┆ s__Mogibacte │
│             ┆ 960486_MAG03 ┆      ┆      ┆          ┆              ┆              ┆ rium_A       │
│             ┆ _96_2        ┆      ┆      ┆          ┆              ┆              ┆ kristiansen… │
│ SRR11489783 ┆ AtH2023_SRR8 ┆ 375  ┆ 375  ┆ 1.0      ┆ 11142.842667 ┆ 11142.842667 ┆ s__Mogibacte │
│             ┆ 960486_MAG03 ┆      ┆      ┆          ┆              ┆              ┆ rium_A       │
│             ┆ _96_2        ┆      ┆      ┆          ┆              ┆              ┆ kristiansen… │
│ …           ┆ …            ┆ …    ┆ …    ┆ …        ┆ …            ┆ …            ┆ …            │
│ SRR8960492  ┆ AtH2023_ERR3 ┆ 4197 ┆ 2    ┆ 0.000477 ┆ 0.000477     ┆ 1.0          ┆ s__Prevotell │
│             ┆ 211862_MAG2_ ┆      ┆      ┆          ┆              ┆              ┆ a            │
│             ┆ 81_1         ┆      ┆      ┆          ┆              ┆              ┆ sp002251295  │
│ SRR8960379  ┆ HF986301.1_5 ┆ 2430 ┆ 1    ┆ 0.000412 ┆ 0.000412     ┆ 1.0          ┆ s__Cryptobac │
│             ┆ 6            ┆      ┆      ┆          ┆              ┆              ┆ teroides     │
│             ┆              ┆      ┆      ┆          ┆              ┆              ┆ sp0004326…   │
│ SRR11124923 ┆ CAVAXB010000 ┆ 2745 ┆ 1    ┆ 0.000364 ┆ 0.000364     ┆ 1.0          ┆ s__Sodaliphi │
│             ┆ 020.1_12     ┆      ┆      ┆          ┆              ┆              ┆ lus          │
│             ┆              ┆      ┆      ┆          ┆              ┆              ┆ sp004557565  │
│ SRR11125497 ┆ CAKUPF010000 ┆ 3765 ┆ 1    ┆ 0.000266 ┆ 0.000266     ┆ 1.0          ┆ s__Sodaliphi │
│             ┆ 012.1_63     ┆      ┆      ┆          ┆              ┆              ┆ lus          │
│             ┆              ┆      ┆      ┆          ┆              ┆              ┆ sp004557565  │
│ SRR8655118  ┆ AtH2023_ERR3 ┆ 4197 ┆ 1    ┆ 0.000238 ┆ 0.000238     ┆ 1.0          ┆ s__Prevotell │
│             ┆ 211862_MAG2_ ┆      ┆      ┆          ┆              ┆              ┆ a            │
│             ┆ 81_1         ┆      ┆      ┆          ┆              ┆              ┆ sp002251295  │
└─────────────┴──────────────┴──────┴──────┴──────────┴──────────────┴──────────────┴──────────────┘

## Summarize our mapping breadth results across all the metagenomes

This is for figuring out which genes to manually curate.

In [14]:
# require 10% of each gene to be covered by at least one read
BREADTH_CUTOFF = 0.1

In [15]:
# aggregate across all metagenomes;
# calculate fraction of metagenomes for which gene mapping exceeds our breadth cutoff
agg_df = depth_df.group_by(['species', 'gene']).agg(
    # get fraction of columns where breadth is greater than cutoff as 'f'
    ((pl.col("breadth") >= BREADTH_CUTOFF).sum() / pl.col("breadth").len()).alias("f"),
#    (pl.col("depth").filter(pl.col("depth").is_not_nan()).mean()),
)
agg_df

shape: (9_184, 3)
┌─────────────────────────────────┬─────────────────────────────────┬──────┐
│ species                         ┆ gene                            ┆ f    │
│ ---                             ┆ ---                             ┆ ---  │
│ str                             ┆ str                             ┆ f64  │
╞═════════════════════════════════╪═════════════════════════════════╪══════╡
│ s__Cryptobacteroides sp9005469… ┆ AtH2023_SRR17241489_MAG21_95_2  ┆ 0.66 │
│ s__Cryptobacteroides sp9005469… ┆ AtH2023_ERR8314740_MAG4_323_4   ┆ 0.82 │
│ s__Sodaliphilus sp004557565     ┆ AtH2023_ERR3211826_MAG3_143_3   ┆ 0.92 │
│ s__Prevotella sp002251295       ┆ AtH2023_SRR5976187_MAG13_152_1… ┆ 0.87 │
│ s__Colivicinus sp002299675      ┆ CAMFSL010000016.1_44            ┆ 0.68 │
│ …                               ┆ …                               ┆ …    │
│ s__Cryptobacteroides sp0004349… ┆ JAXXGF010000032.1_4             ┆ 0.86 │
│ s__Cryptobacteroides sp9005469… ┆ AtH2023_ERR3211746_MAG11_207_1  ┆ 0.86 │
│ s__Sodaliphilus sp004557565     ┆ AtH2023_SRR7182061_MAG3_144_1   ┆ 0.71 │
│ s__Prevotella sp000434975       ┆ JALETN010000006.1_5             ┆ 0.79 │
│ s__Prevotella sp000434975       ┆ JAXWUJ010000075.1_4             ┆ 0.11 │
└─────────────────────────────────┴─────────────────────────────────┴──────┘

## Investigate specific species

In [19]:

SPECIES_INVESTIGATE = {
    's__Floccifex porci': 'BAD',
    's__Bariatricus sp004560705': 'BAD',
    's__Cryptobacteroides sp034089285': 'BAD',
    's__UBA2868 sp004552595': 'BAD',
    's__Mogibacterium_A kristiansenii': 'BAD',
    's__JAFBIX01 sp021531895': 'WTF',                      # no single copy gene yet.
}

In [24]:
ofp = open('../candidate-genes-for-review.csv', 'w', newline='')
w = csv.writer(ofp)

# print information out by species
for species in sorted(agg_df['species'].unique()):
    if species not in SPECIES_INVESTIGATE:
        continue
        
    print(species)
    foo_df = agg_df.filter(pl.col("species") == species)
    foo_df = foo_df.sort(by='f', descending=True).filter(pl.col('f') > 0.0)
    print(foo_df)

    for name in foo_df.head(50)['gene'].to_list():
        w.writerow(['0', '0', species, '(not reviewed)', name, '(not reviewed)'])

ofp.close()

s__Bariatricus sp004560705
shape: (461, 3)
┌────────────────────────────┬─────────────────────────────────┬──────┐
│ species                    ┆ gene                            ┆ f    │
│ ---                        ┆ ---                             ┆ ---  │
│ str                        ┆ str                             ┆ f64  │
╞════════════════════════════╪═════════════════════════════════╪══════╡
│ s__Bariatricus sp004560705 ┆ CAMEGG010000087.1_1             ┆ 1.0  │
│ s__Bariatricus sp004560705 ┆ AtH2023_ERR1135319_MAG02_256_1… ┆ 0.99 │
│ s__Bariatricus sp004560705 ┆ AtH2023_ERR1135319_MAG02_116_2… ┆ 0.99 │
│ s__Bariatricus sp004560705 ┆ AtH2023_ERR1135319_MAG02_177_1… ┆ 0.99 │
│ s__Bariatricus sp004560705 ┆ AtH2023_ERR1135319_MAG02_177_1… ┆ 0.99 │
│ …                          ┆ …                               ┆ …    │
│ s__Bariatricus sp004560705 ┆ CAMEYJ010000133.1_7             ┆ 0.48 │
│ s__Bariatricus sp004560705 ┆ AtH2023_SRR17241646_MAG19_72_1… ┆ 0.48 │
│ s__Bariatricus sp004560705 ┆ AtH2023_SRR8960429_MAG5_100_5   ┆ 0.43 │
│ s__Bariatricus sp004560705 ┆ AtH2023_SRR14369156_MAG13_184_… ┆ 0.34 │
│ s__Bariatricus sp004560705 ┆ AtH2023_SRR8960126_MAG22_79_2   ┆ 0.27 │
└────────────────────────────┴─────────────────────────────────┴──────┘
s__Cryptobacteroides sp034089285
shape: (440, 3)
┌─────────────────────────────────┬─────────────────────────────────┬──────┐
│ species                         ┆ gene                            ┆ f    │
│ ---                             ┆ ---                             ┆ ---  │
│ str                             ┆ str                             ┆ f64  │
╞═════════════════════════════════╪═════════════════════════════════╪══════╡
│ s__Cryptobacteroides sp0340892… ┆ SFLF01000306.1_1                ┆ 1.0  │
│ s__Cryptobacteroides sp0340892… ┆ AtH2023_SRR7182051_MAG7_42_14   ┆ 0.96 │
│ s__Cryptobacteroides sp0340892… ┆ AtH2023_SRR21357591_MAG09_215_… ┆ 0.95 │
│ s__Cryptobacteroides sp0340892… ┆ AtH2023_SRR8960445_MAG05_105_2  ┆ 0.95 │
│ s__Cryptobacteroides sp0340892… ┆ AtH2023_SRR7182051_MAG7_55_13   ┆ 0.95 │
│ …                               ┆ …                               ┆ …    │
│ s__Cryptobacteroides sp0340892… ┆ AtH2023_ERR8314738_MAG5_103_1   ┆ 0.3  │
│ s__Cryptobacteroides sp0340892… ┆ AtH2023_SRR8960790_MAG22_190_1  ┆ 0.27 │
│ s__Cryptobacteroides sp0340892… ┆ AtH2023_SRR8960595_MAG09_13_3   ┆ 0.21 │
│ s__Cryptobacteroides sp0340892… ┆ SFXG01000049.1_3                ┆ 0.15 │
│ s__Cryptobacteroides sp0340892… ┆ AtH2023_SRR17241623_MAG14_153_… ┆ 0.02 │
└─────────────────────────────────┴─────────────────────────────────┴──────┘
s__Floccifex porci
shape: (17, 3)
┌────────────────────┬─────────────────────────────────┬──────┐
│ species            ┆ gene                            ┆ f    │
│ ---                ┆ ---                             ┆ ---  │
│ str                ┆ str                             ┆ f64  │
╞════════════════════╪═════════════════════════════════╪══════╡
│ s__Floccifex porci ┆ AtH2023_SRR17241619_MAG38_26_1  ┆ 0.89 │
│ s__Floccifex porci ┆ AtH2023_SRR17241619_MAG38_55_1… ┆ 0.82 │
│ s__Floccifex porci ┆ AtH2023_SRR8960733_MAG28_17_5   ┆ 0.8  │
│ s__Floccifex porci ┆ AtH2023_SRR17241619_MAG38_31_1… ┆ 0.79 │
│ s__Floccifex porci ┆ AtH2023_SRR17241619_MAG38_101_… ┆ 0.77 │
│ …                  ┆ …                               ┆ …    │
│ s__Floccifex porci ┆ AtH2023_SRR8960790_MAG16_117_5… ┆ 0.62 │
│ s__Floccifex porci ┆ AtH2023_SRR8960733_MAG28_38_11  ┆ 0.61 │
│ s__Floccifex porci ┆ AtH2023_SRR8960611_MAG09_37_13  ┆ 0.6  │
│ s__Floccifex porci ┆ AtH2023_SRR17241641_MAG18_158_… ┆ 0.51 │
│ s__Floccifex porci ┆ NZ_JAXEST010000029.1_106        ┆ 0.39 │
└────────────────────┴─────────────────────────────────┴──────┘
s__JAFBIX01 sp021531895
shape: (1, 3)
┌─────────────────────────┬────────────────────────────────┬──────┐
│ species                 ┆ gene                           ┆ f    │
│ ---                     ┆ ---                            ┆ ---  │
│ str                     ┆ str                            ┆ f64  │
╞═════════════════════════╪════════════════════════════════╪══════╡
│ s__JAFBIX01 sp021531895 ┆ AtH2023_SRR8960206_MAG05_101_1 ┆ 0.86 │
└─────────────────────────┴────────────────────────────────┴──────┘
s__Mogibacterium_A kristiansenii
shape: (21, 3)
┌─────────────────────────────────┬─────────────────────────────────┬──────┐
│ species                         ┆ gene                            ┆ f    │
│ ---                             ┆ ---                             ┆ ---  │
│ str                             ┆ str                             ┆ f64  │
╞═════════════════════════════════╪═════════════════════════════════╪══════╡
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR8960486_MAG03_96_2   ┆ 1.0  │
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR8960591_MAG05_28_1   ┆ 1.0  │
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR11184020_MAG14_3_1   ┆ 0.92 │
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR8960781_MAG03_20_1   ┆ 0.91 │
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR8960721_MAG03_65_3   ┆ 0.87 │
│ …                               ┆ …                               ┆ …    │
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR8960652_MAG18_179_7  ┆ 0.2  │
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR8960301_MAG10_123_3… ┆ 0.18 │
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR8960132_MAG03_87_6   ┆ 0.17 │
│ s__Mogibacterium_A kristiansen… ┆ CABUFZ010000028.1_3             ┆ 0.14 │
│ s__Mogibacterium_A kristiansen… ┆ AtH2023_SRR17241641_MAG31_88_1  ┆ 0.1  │
└─────────────────────────────────┴─────────────────────────────────┴──────┘
s__UBA2868 sp004552595
shape: (740, 3)
┌────────────────────────┬─────────────────────────────────┬──────┐
│ species                ┆ gene                            ┆ f    │
│ ---                    ┆ ---                             ┆ ---  │
│ str                    ┆ str                             ┆ f64  │
╞════════════════════════╪═════════════════════════════════╪══════╡
│ s__UBA2868 sp004552595 ┆ AtH2023_SRR8960665_MAG01_95_4   ┆ 0.98 │
│ s__UBA2868 sp004552595 ┆ AtH2023_SRR8960319_MAG08_10_1   ┆ 0.98 │
│ s__UBA2868 sp004552595 ┆ AtH2023_SRR2329609_MAG3_81_54   ┆ 0.97 │
│ s__UBA2868 sp004552595 ┆ AtH2023_SRR17241584_MAG09_19_1  ┆ 0.97 │
│ s__UBA2868 sp004552595 ┆ AtH2023_SRR5976187_MAG11_100_2… ┆ 0.97 │
│ …                      ┆ …                               ┆ …    │
│ s__UBA2868 sp004552595 ┆ JAUNCM010000005.1_22            ┆ 0.13 │
│ s__UBA2868 sp004552595 ┆ AtH2023_SRR8960831_MAG08_7_11   ┆ 0.06 │
│ s__UBA2868 sp004552595 ┆ JAUNCM010000002.1_19            ┆ 0.05 │
│ s__UBA2868 sp004552595 ┆ AtH2023_ERR1135378_MAG02_387_1  ┆ 0.03 │
│ s__UBA2868 sp004552595 ┆ JAUNCM010000011.1_38            ┆ 0.02 │
└────────────────────────┴─────────────────────────────────┴──────┘