# Core species analysis - primary notebook

In [3]:
import polars as pl

In [4]:
df = (
    pl.scan_parquet('../outputs.cds3/pq/mag+gtdb.cds3.x.3216.manysearch.parquet')
    .filter(pl.col('intersect_hashes') >= 20)
).collect()

In [5]:
df

shape: (2_357_261, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GCA_96360 ┆ 98787da90 ┆ SRR111833 ┆ 0.18467   ┆ … ┆ 0.831609  ┆ 0.922713  ┆ 4656      ┆ 1066419  │
│ 6895 s__M ┆ 33ca08f4a ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ ethanocat ┆ 8e0e553cd ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ell…      ┆ 3be…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_90216 ┆ ca79ba3d2 ┆ SRR111833 ┆ 0.003933  ┆ … ┆ 0.720727  ┆ 0.768183  ┆ 103       ┆ 1066419  │
│ 3005 s__E ┆ b584c0ffd ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ nterococc ┆ c81940fc1 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ us …      ┆ 984…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ SRR111833 ┆ 0.017325  ┆ … ┆ 0.809462  ┆ 0.824381  ┆ 22416     ┆ 1066419  │
│ 6715 s__E ┆ e1634a43c ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_90051 ┆ caef9e116 ┆ SRR111833 ┆ 0.000643  ┆ … ┆ 0.675688  ┆ 0.704729  ┆ 105       ┆ 1066419  │
│ 3975 s__K ┆ e27e60950 ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ lebsiella ┆ 2c15f8f56 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ pn…       ┆ 877…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_03411 ┆ c670dcee3 ┆ SRR111833 ┆ 0.101147  ┆ … ┆ 0.810399  ┆ 0.896637  ┆ 631       ┆ 1066419  │
│ 8145 s__B ┆ e5cbe4262 ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ utyricimo ┆ 71f4a3a7b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ nas…      ┆ 589…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GCA_04167 ┆ 03f6ba47d ┆ SRR143691 ┆ 0.025259  ┆ … ┆ 0.723287  ┆ 0.839315  ┆ 196       ┆ 7255242  │
│ 5925 s__P ┆ e50e2dd2a ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ aracholep ┆ 1ff2d60c2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ las…      ┆ 4a5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_01750 ┆ 61144402e ┆ SRR143691 ┆ 0.134986  ┆ … ┆ 0.756227  ┆ 0.909045  ┆ 67        ┆ 7255242  │
│ 8245      ┆ 05944f3e9 ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__NHYM01 ┆ 7c3969a96 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0175…   ┆ 231…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_93429 ┆ 6fa54e46f ┆ SRR143691 ┆ 0.018105  ┆ … ┆ 0.718621  ┆ 0.82611   ┆ 102       ┆ 7255242  │
│ 5335 s__E ┆ 6187a0282 ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ ubacteriu ┆ c6cddc1d3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ m_F…      ┆ 048…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_94707 ┆ 353411538 ┆ SRR143691 ┆ 0.627321  ┆ … ┆ 0.836401  ┆ 0.97804   ┆ 21631     ┆ 7255242  │
│ 2185 s__C ┆ 20c9ef1f6 ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ lostridiu ┆ 55092a011 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ m s…      ┆ 354…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_02161 ┆ 1d4ec9840 ┆ SRR143691 ┆ 0.227723  ┆ … ┆ 0.782937  ┆ 0.931967  ┆ 320       ┆ 7255242  │
│ 6655 s__U ┆ 361f4f7b1 ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ BA2903    ┆ c9fc3945c ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp900…    ┆ 62b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
n_acc = df['match_name'].n_unique()
by_species = df.group_by('query_name').agg(
    freq=pl.len() / n_acc
)

In [7]:
with pl.Config(tbl_rows=-1):
    print(by_species.sort('freq', descending=True).filter(pl.col('freq') >= 0.95))

shape: (17, 2)
┌─────────────────────────────────┬──────────┐
│ query_name                      ┆ freq     │
│ ---                             ┆ ---      │
│ str                             ┆ f64      │
╞═════════════════════════════════╪══════════╡
│ GCF_001256715 s__Escherichia c… ┆ 0.992537 │
│ GCA_945834365 s__Sodaliphilus … ┆ 0.990983 │
│ GCF_028308525 s__Lactobacillus… ┆ 0.990361 │
│ GCA_946007015 s__UBA2868 sp004… ┆ 0.979167 │
│ GCA_927798655 s__Cryptobactero… ┆ 0.978545 │
│ GCA_034171835 s__Mogibacterium… ┆ 0.977301 │
│ GCA_945872445 s__JAFBIX01 sp02… ┆ 0.974502 │
│ GCA_946408405 s__Fimisoma sp00… ┆ 0.973259 │
│ GCA_945501735 s__Prevotella sp… ┆ 0.968595 │
│ GCA_945876695 s__Floccifex por… ┆ 0.968284 │
│ GCA_004561115 s__Cryptobactero… ┆ 0.968284 │
│ GCA_945877245 s__Bariatricus s… ┆ 0.966418 │
│ GCA_022781365 s__Colivicinus s… ┆ 0.958333 │
│ GCA_945932635 s__Cryptobactero… ┆ 0.956468 │
│ GCA_945938975 s__Ornithospiroc… ┆ 0.955224 │
│ GCA_934726065 s__Cryptobactero… ┆ 0.952425 │
│ GCA_028727695 s__Prevotella sp… ┆ 0.95056  │
└─────────────────────────────────┴──────────┘

In [8]:
OLD_NAMES = [ x.strip() for x in open('../../2025-workflow-core99/inputs.cds/names.list') ]
OLD_NAMES_PLUS = [ x.strip() for x in open('../../2025-workflow-core99/inputs.cds/names-plus.list') ]

In [9]:
OLD_NAMES

['s__Bariatricus sp004560705',
 's__Colivicinus sp002299675',
 's__Cryptobacteroides sp000432655',
 's__Cryptobacteroides sp000434935',
 's__Cryptobacteroides sp034089285',
 's__Cryptobacteroides sp900546925',
 's__Fimisoma sp002320005',
 's__Floccifex porci',
 's__JAFBIX01 sp021531895',
 's__Lactobacillus amylovorus',
 's__Mogibacterium_A kristiansenii',
 's__Ornithospirochaeta sp022785155',
 's__Prevotella sp000434975',
 's__Prevotella sp002251295',
 's__Sodaliphilus sp004557565',
 's__UBA2868 sp004552595']

In [10]:
xx_df = (
    by_species
    .with_columns(species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " "))
).filter(~(pl.col('species_name').is_in(OLD_NAMES)))
xx_df.filter(pl.col('freq') >= 0.95)

shape: (1, 3)
┌─────────────────────────────────┬──────────┬─────────────────────┐
│ query_name                      ┆ freq     ┆ species_name        │
│ ---                             ┆ ---      ┆ ---                 │
│ str                             ┆ f64      ┆ str                 │
╞═════════════════════════════════╪══════════╪═════════════════════╡
│ GCF_001256715 s__Escherichia c… ┆ 0.992537 ┆ s__Escherichia coli │
└─────────────────────────────────┴──────────┴─────────────────────┘

In [11]:
len(OLD_NAMES)

16

In [12]:
xx_df = (
    by_species
    .with_columns(species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " "))
).filter((pl.col('species_name').is_in(OLD_NAMES_PLUS)))
with pl.Config(tbl_rows=-1):
    print(xx_df.sort('freq', descending=True))

shape: (27, 3)
┌─────────────────────────────────┬──────────┬─────────────────────────────────┐
│ query_name                      ┆ freq     ┆ species_name                    │
│ ---                             ┆ ---      ┆ ---                             │
│ str                             ┆ f64      ┆ str                             │
╞═════════════════════════════════╪══════════╪═════════════════════════════════╡
│ GCA_945834365 s__Sodaliphilus … ┆ 0.990983 ┆ s__Sodaliphilus sp004557565     │
│ GCF_028308525 s__Lactobacillus… ┆ 0.990361 ┆ s__Lactobacillus amylovorus     │
│ GCA_946007015 s__UBA2868 sp004… ┆ 0.979167 ┆ s__UBA2868 sp004552595          │
│ GCA_927798655 s__Cryptobactero… ┆ 0.978545 ┆ s__Cryptobacteroides sp9005469… │
│ GCA_034171835 s__Mogibacterium… ┆ 0.977301 ┆ s__Mogibacterium_A kristiansen… │
│ GCA_945872445 s__JAFBIX01 sp02… ┆ 0.974502 ┆ s__JAFBIX01 sp021531895         │
│ GCA_946408405 s__Fimisoma sp00… ┆ 0.973259 ┆ s__Fimisoma sp002320005         │
│ GCA_945501735 s__Prevotella sp… ┆ 0.968595 ┆ s__Prevotella sp002251295       │
│ GCA_945876695 s__Floccifex por… ┆ 0.968284 ┆ s__Floccifex porci              │
│ GCA_004561115 s__Cryptobactero… ┆ 0.968284 ┆ s__Cryptobacteroides sp0340892… │
│ GCA_945877245 s__Bariatricus s… ┆ 0.966418 ┆ s__Bariatricus sp004560705      │
│ GCA_022781365 s__Colivicinus s… ┆ 0.958333 ┆ s__Colivicinus sp002299675      │
│ GCA_945932635 s__Cryptobactero… ┆ 0.956468 ┆ s__Cryptobacteroides sp0004349… │
│ GCA_945938975 s__Ornithospiroc… ┆ 0.955224 ┆ s__Ornithospirochaeta sp022785… │
│ GCA_934726065 s__Cryptobactero… ┆ 0.952425 ┆ s__Cryptobacteroides sp0004326… │
│ GCA_028727695 s__Prevotella sp… ┆ 0.95056  ┆ s__Prevotella sp000434975       │
│ GCA_034086705 s__UMGS1225 sp03… ┆ 0.782338 ┆ s__UMGS1225 sp034086705         │
│ GCA_963658475 s__Ruminococcus_… ┆ 0.612251 ┆ s__Ruminococcus_C sp000433635   │
│ GCA_945918795 s__SIG351 sp9459… ┆ 0.528607 ┆ s__SIG351 sp945918795           │
│ GCA_022655115 s__Bifidobacteri… ┆ 0.4801   ┆ s__Bifidobacterium thermacidop… │
│ GCA_017937505 s__Ventricola sp… ┆ 0.357898 ┆ s__Ventricola sp017937505       │
│ GCA_945872375 s__Blautia_A sp9… ┆ 0.355721 ┆ s__Blautia_A sp945872375        │
│ GCA_016302215 s__CAG-873 sp016… ┆ 0.352612 ┆ s__CAG-873 sp016302215          │
│ GCA_036737635 s__Phascolarctob… ┆ 0.344838 ┆ s__Phascolarctobacterium_A suc… │
│ GCA_934167445 s__CAG-269 sp014… ┆ 0.308769 ┆ s__CAG-269 sp014846485          │
│ GCA_037455835 s__CAG-465 sp000… ┆ 0.2301   ┆ s__CAG-465 sp000433755          │
│ GCF_028720085 s__Ruminococcoid… ┆ 0.222015 ┆ s__Ruminococcoides sp902766885  │
└─────────────────────────────────┴──────────┴─────────────────────────────────┘

In [13]:
len(OLD_NAMES_PLUS)

27

## Ask questions about core species in metagenomes by metagenome

In [14]:
by_acc = (
    df
    .with_columns(
        species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " ")
    )
    .filter(pl.col('species_name').is_in(OLD_NAMES))
    .group_by('match_name').agg(
        n_core=pl.len()
    )
).sort('n_core')

In [15]:
by_acc

shape: (3_210, 2)
┌─────────────┬────────┐
│ match_name  ┆ n_core │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ SRR12795729 ┆ 1      │
│ SRR12795774 ┆ 1      │
│ SRR12795782 ┆ 1      │
│ SRR12795740 ┆ 1      │
│ SRR12795783 ┆ 1      │
│ …           ┆ …      │
│ SRR11183573 ┆ 16     │
│ SRR11126323 ┆ 16     │
│ SRR17241519 ┆ 16     │
│ SRR14812370 ┆ 16     │
│ SRR8960562  ┆ 16     │
└─────────────┴────────┘

In [16]:
low_core_acc = by_acc.filter(pl.col('n_core') < 10)

In [17]:
metadata_df = (
    pl.scan_parquet("/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet")
    .filter(pl.col("acc") != "NP")
    .filter(pl.col("assay_type") == "WGS")
#    .select(["acc", "organism", "bioproject", "mbases", "host", "project_name"]) 
    .collect()
)

In [18]:
low_core_acc = low_core_acc.rename({'match_name': 'acc'})

In [19]:
low_core_acc2 = low_core_acc.join(metadata_df, on='acc', how='left')
low_core_acc2

shape: (57, 68)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ n_core ┆ sample_nam ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---    ┆ e          ┆ me_sam    ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ list[str] ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆        ┆            ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1279572 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 246703483 ┆ "2020-10- ┆ null      ┆ "16396807 │
│ 9          ┆        ┆ 412        ┆           ┆   ┆ 9         ┆ 08T12:26: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279577 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 207750152 ┆ "2020-10- ┆ null      ┆ "16396805 │
│ 4          ┆        ┆ 406        ┆           ┆   ┆ 7         ┆ 08T12:22: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279578 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 290040765 ┆ "2020-10- ┆ null      ┆ "16396824 │
│ 2          ┆        ┆ 424        ┆           ┆   ┆ 6         ┆ 08T12:24: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279574 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 282304744 ┆ "2020-10- ┆ null      ┆ "16396806 │
│ 0          ┆        ┆ 409        ┆           ┆   ┆ 0         ┆ 08T12:31: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279578 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 269320240 ┆ "2020-10- ┆ null      ┆ "16396823 │
│ 3          ┆        ┆ 421        ┆           ┆   ┆ 6         ┆ 08T12:28: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR1804890 ┆ 9      ┆ Control3   ┆ []        ┆ … ┆ 350782295 ┆ "2022-02- ┆ null      ┆ "25980734 │
│ 8          ┆        ┆            ┆           ┆   ┆ 4         ┆ 18T08:18: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804891 ┆ 9      ┆ Berberine5 ┆ []        ┆ … ┆ 545845990 ┆ "2022-02- ┆ null      ┆ "25980742 │
│ 0          ┆        ┆            ┆           ┆   ┆ 8         ┆ 18T08:33: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1112525 ┆ 9      ┆ Ja31/14277 ┆ []        ┆ … ┆ 307295762 ┆ "2020-02- ┆ null      ┆ "11097684 │
│ 0          ┆        ┆            ┆           ┆   ┆           ┆ 20T21:10: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8960541 ┆ 9      ┆ Ja31/29951 ┆ []        ┆ … ┆ 151269173 ┆ "2019-04- ┆ null      ┆ "11097774 │
│            ┆        ┆            ┆           ┆   ┆ 1         ┆ 26T03:21: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1118404 ┆ 9      ┆ Ja31/14277 ┆ []        ┆ … ┆ 342710570 ┆ "2020-02- ┆ null      ┆ "11097684 │
│ 6          ┆        ┆            ┆           ┆   ┆           ┆ 26T03:36: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [20]:
low_core_acc2.group_by('bioproject').agg(
    pl.len()
).sort('len')

shape: (9, 2)
┌─────────────┬─────┐
│ bioproject  ┆ len │
│ ---         ┆ --- │
│ str         ┆ u32 │
╞═════════════╪═════╡
│ PRJNA741980 ┆ 1   │
│ PRJNA629856 ┆ 1   │
│ PRJNA471402 ┆ 1   │
│ PRJNA408025 ┆ 3   │
│ PRJEB31650  ┆ 5   │
│ PRJNA807368 ┆ 7   │
│ PRJNA373834 ┆ 8   │
│ PRJNA526405 ┆ 14  │
│ PRJNA668104 ┆ 17  │
└─────────────┴─────┘

## Explore saturation

In [21]:
sat_df = pl.read_parquet('../../2025-ccbaumler-wort-gathering/wort-sra-signature-saturation.parquet')

In [22]:
sat_df

shape: (5_149_985, 5)
┌─────────────────────────────────┬─────────────┬─────────────┬─────────────┬─────────────────────┐
│ filepath                        ┆ signature   ┆ novel_count ┆ total_count ┆ sequence_saturation │
│ ---                             ┆ ---         ┆ ---         ┆ ---         ┆ ---                 │
│ str                             ┆ str         ┆ i64         ┆ i64         ┆ f64                 │
╞═════════════════════════════════╪═════════════╪═════════════╪═════════════╪═════════════════════╡
│ /group/ctbrowngrp/irber/data/w… ┆ SRR33867156 ┆ 23507       ┆ 397539      ┆ 0.940869            │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR4022268  ┆ 27896       ┆ 308529      ┆ 0.909584            │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR3771976  ┆ 223         ┆ 3174        ┆ 0.929742            │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR11996469 ┆ 20          ┆ 40          ┆ 0.5                 │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR10755277 ┆ 3185        ┆ 26976       ┆ 0.881932            │
│ …                               ┆ …           ┆ …           ┆ …           ┆ …                   │
│ /group/ctbrowngrp/irber/data/w… ┆ SRR9934015  ┆ 57128       ┆ 286525      ┆ 0.800618            │
│ /group/ctbrowngrp/irber/data/w… ┆ SRR7588346  ┆ 67307       ┆ 409191      ┆ 0.835512            │
│ /group/ctbrowngrp/irber/data/w… ┆ SRR10432619 ┆ 88275       ┆ 942001      ┆ 0.90629             │
│ /group/ctbrowngrp/irber/data/w… ┆ SRR4027653  ┆ 800444      ┆ 1241468     ┆ 0.355244            │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR11569305 ┆ 728129      ┆ 5832378     ┆ 0.875157            │
└─────────────────────────────────┴─────────────┴─────────────┴─────────────┴─────────────────────┘

In [23]:
sat_df2 = df.join(sat_df, left_on='match_name', right_on='signature',
                  how='left')

In [24]:
zz = []
for min_sat in (0.25, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9):
    xx_df = sat_df2.filter(pl.col('sequence_saturation') >= min_sat)
    n_acc = xx_df['match_name'].n_unique()
    xx2_df= df.group_by('query_name').agg(
        freq=pl.len() / n_acc
    ).filter(pl.col('freq') >= 0.95)
    zz.append(dict(min=min_sat, num_metag=n_acc, num_core95=len(xx2_df)))
    #print(min_sat, n_acc, len(xx2_df))

zz_df = pl.DataFrame(zz)

In [25]:
zz_df

shape: (8, 3)
┌──────┬───────────┬────────────┐
│ min  ┆ num_metag ┆ num_core95 │
│ ---  ┆ ---       ┆ ---        │
│ f64  ┆ i64       ┆ i64        │
╞══════╪═══════════╪════════════╡
│ 0.25 ┆ 3216      ┆ 17         │
│ 0.3  ┆ 3215      ┆ 17         │
│ 0.4  ┆ 3206      ┆ 18         │
│ 0.5  ┆ 3065      ┆ 38         │
│ 0.6  ┆ 2251      ┆ 269        │
│ 0.7  ┆ 1244      ┆ 737        │
│ 0.8  ┆ 366       ┆ 1724       │
│ 0.9  ┆ 37        ┆ 3116       │
└──────┴───────────┴────────────┘