# Core species analysis - GTDB only

In [1]:
import polars as pl

In [2]:
df = (
    pl.scan_parquet('../outputs.cds3/pq/gtdb.cds3.x.3216.manysearch.parquet')
    .filter(pl.col('intersect_hashes') >= 20)
    .with_columns(species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " "))
).collect()

In [3]:
df

shape: (2_385_857, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ max_conta ┆ n_weighte ┆ total_wei ┆ species_ │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ inment_an ┆ d_found   ┆ ghted_has ┆ name     │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ i         ┆ ---       ┆ hes       ┆ ---      │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GCA_96360 ┆ e1e78e249 ┆ SRR111833 ┆ 0.224552  ┆ … ┆ 0.931344  ┆ 15090     ┆ 995049    ┆ s__Metha │
│ 6895 s__M ┆ a6a2a11a5 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆ nocatell │
│ ethanocat ┆ d4838d468 ┆           ┆           ┆   ┆           ┆           ┆           ┆ a        │
│ ell…      ┆ 32e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ smithii  │
│ GCF_90216 ┆ 237581605 ┆ SRR111833 ┆ 0.027679  ┆ … ┆ 0.842979  ┆ 2657      ┆ 995049    ┆ s__Enter │
│ 3005 s__E ┆ 496a55a46 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆ ococcus  │
│ nterococc ┆ 85225090f ┆           ┆           ┆   ┆           ┆           ┆           ┆ faecalis │
│ us …      ┆ eb3…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 1f70baaf4 ┆ SRR111833 ┆ 0.005168  ┆ … ┆ 0.778231  ┆ 3754      ┆ 995049    ┆ s__Esche │
│ 6715 s__E ┆ 79ba33ceb ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆ richia   │
│ scherichi ┆ 65afba904 ┆           ┆           ┆   ┆           ┆           ┆           ┆ coli     │
│ a c…      ┆ 327…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_03411 ┆ d41465962 ┆ SRR111833 ┆ 0.181149  ┆ … ┆ 0.921867  ┆ 1601      ┆ 995049    ┆ s__Butyr │
│ 8145 s__B ┆ f39cbe33f ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆ icimonas │
│ utyricimo ┆ 972d60088 ┆           ┆           ┆   ┆           ┆           ┆           ┆ virosa   │
│ nas…      ┆ 7b7…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_90521 ┆ 202150856 ┆ SRR111833 ┆ 0.073897  ┆ … ┆ 0.883335  ┆ 179       ┆ 995049    ┆ s__Metha │
│ 2675 s__M ┆ dd3473c67 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆ nomethyl │
│ ethanomet ┆ 8da6a3c48 ┆           ┆           ┆   ┆           ┆           ┆           ┆ ophilus  │
│ hyl…      ┆ 206…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ alvi     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GCA_02161 ┆ 56d4fe6e5 ┆ SRR172416 ┆ 0.257359  ┆ … ┆ 0.937412  ┆ 674       ┆ 14000869  ┆ s__HGM11 │
│ 8115 s__H ┆ ac7a73f0b ┆ 61        ┆           ┆   ┆           ┆           ┆           ┆ 372 sp90 │
│ GM11372   ┆ af4fca85b ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0767715  │
│ sp90…     ┆ 5ee…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_02276 ┆ 98c316eb1 ┆ SRR172416 ┆ 0.317528  ┆ … ┆ 0.946837  ┆ 677       ┆ 14000869  ┆ s__Anaer │
│ 9785 s__A ┆ 01ac31a2e ┆ 61        ┆           ┆   ┆           ┆           ┆           ┆ obutyric │
│ naerobuty ┆ 7ed7b7ecb ┆           ┆           ┆   ┆           ┆           ┆           ┆ um sp022 │
│ ric…      ┆ 712…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 769785   │
│ GCA_90246 ┆ ba91244e6 ┆ SRR172416 ┆ 0.029575  ┆ … ┆ 0.845642  ┆ 52        ┆ 14000869  ┆ s__Juton │
│ 2135 s__J ┆ 1d2de47e9 ┆ 61        ┆           ┆   ┆           ┆           ┆           ┆ gia sp93 │
│ utongia   ┆ 1a38676bd ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4339135  │
│ sp93…     ┆ 14f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_03724 ┆ 6f554c011 ┆ SRR172416 ┆ 0.23741   ┆ … ┆ 0.933817  ┆ 289       ┆ 14000869  ┆ s__CAG-4 │
│ 8775 s__C ┆ 1fcbfa05f ┆ 61        ┆           ┆   ┆           ┆           ┆           ┆ 92 sp000 │
│ AG-492    ┆ ae87d481f ┆           ┆           ┆   ┆           ┆           ┆           ┆ 434015   │
│ sp000…    ┆ b0c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_93445 ┆ f9e84410b ┆ SRR172416 ┆ 0.455184  ┆ … ┆ 0.963215  ┆ 2346      ┆ 14000869  ┆ s__RUG80 │
│ 4875      ┆ e0d70cddd ┆ 61        ┆           ┆   ┆           ┆           ┆           ┆ 6 sp0162 │
│ s__RUG806 ┆ 5dac49245 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 97645    │
│ sp0162…   ┆ 0b5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
n_acc = df['match_name'].n_unique()
by_species = df.group_by('species_name').agg(
    freq=pl.len() / n_acc
)

In [5]:
SPECIES_ABOVE_95 = set(by_species.filter(pl.col('freq') >= 0.95)['species_name'])

In [6]:
CORE_NAMES=set([ x.strip() for x in open('../inputs.branchwater/names.list') ])

In [7]:
CORE_NAMES

{'s__Bariatricus sp004560705',
 's__Colivicinus sp002299675',
 's__Cryptobacteroides sp000432655',
 's__Cryptobacteroides sp000434935',
 's__Cryptobacteroides sp034089285',
 's__Cryptobacteroides sp900546925',
 's__Fimisoma sp002320005',
 's__Floccifex porci',
 's__JAFBIX01 sp021531895',
 's__Lactobacillus amylovorus',
 's__Mogibacterium_A kristiansenii',
 's__Ornithospirochaeta sp022785155',
 's__Prevotella sp000434975',
 's__Prevotella sp002251295',
 's__Sodaliphilus sp004557565',
 's__UBA2868 sp004552595'}

In [8]:
len(CORE_NAMES.intersection(SPECIES_ABOVE_95))

11

In [9]:
print(CORE_NAMES - SPECIES_ABOVE_95)
len(CORE_NAMES - SPECIES_ABOVE_95)

{'s__Floccifex porci', 's__Bariatricus sp004560705', 's__JAFBIX01 sp021531895', 's__UBA2868 sp004552595', 's__Mogibacterium_A kristiansenii'}

5

In [10]:
print(SPECIES_ABOVE_95 - CORE_NAMES)
len(SPECIES_ABOVE_95 - CORE_NAMES)

{'s__Escherichia coli', 's__Prevotella sp900548195', 's__CAG-170 sp002404795'}

3

In [11]:
with pl.Config(tbl_rows=-1):
    print(by_species.sort('freq', descending=True).filter(pl.col('freq') >= 0.95))

shape: (14, 2)
┌─────────────────────────────────┬──────────┐
│ species_name                    ┆ freq     │
│ ---                             ┆ ---      │
│ str                             ┆ f64      │
╞═════════════════════════════════╪══════════╡
│ s__Escherichia coli             ┆ 0.994403 │
│ s__Sodaliphilus sp004557565     ┆ 0.990361 │
│ s__Cryptobacteroides sp9005469… ┆ 0.978856 │
│ s__Cryptobacteroides sp0340892… ┆ 0.978856 │
│ s__Lactobacillus amylovorus     ┆ 0.976368 │
│ s__Fimisoma sp002320005         ┆ 0.973881 │
│ s__Cryptobacteroides sp0004349… ┆ 0.968595 │
│ s__Prevotella sp002251295       ┆ 0.962687 │
│ s__Prevotella sp000434975       ┆ 0.960199 │
│ s__Cryptobacteroides sp0004326… ┆ 0.956468 │
│ s__Ornithospirochaeta sp022785… ┆ 0.956157 │
│ s__Colivicinus sp002299675      ┆ 0.954913 │
│ s__CAG-170 sp002404795          ┆ 0.951182 │
│ s__Prevotella sp900548195       ┆ 0.95056  │
└─────────────────────────────────┴──────────┘

In [12]:
xx_df = (
    by_species
).filter(~(pl.col('species_name').is_in(CORE_NAMES)))
xx_df.filter(pl.col('freq') >= 0.95)

shape: (3, 2)
┌───────────────────────────┬──────────┐
│ species_name              ┆ freq     │
│ ---                       ┆ ---      │
│ str                       ┆ f64      │
╞═══════════════════════════╪══════════╡
│ s__Prevotella sp900548195 ┆ 0.95056  │
│ s__Escherichia coli       ┆ 0.994403 │
│ s__CAG-170 sp002404795    ┆ 0.951182 │
└───────────────────────────┴──────────┘

In [13]:
xx_df = (
    by_species
).filter((pl.col('species_name').is_in(CORE_NAMES)))
xx_df.filter(pl.col('freq') >= 0.95)

shape: (11, 2)
┌─────────────────────────────────┬──────────┐
│ species_name                    ┆ freq     │
│ ---                             ┆ ---      │
│ str                             ┆ f64      │
╞═════════════════════════════════╪══════════╡
│ s__Sodaliphilus sp004557565     ┆ 0.990361 │
│ s__Ornithospirochaeta sp022785… ┆ 0.956157 │
│ s__Cryptobacteroides sp0004349… ┆ 0.968595 │
│ s__Lactobacillus amylovorus     ┆ 0.976368 │
│ s__Fimisoma sp002320005         ┆ 0.973881 │
│ …                               ┆ …        │
│ s__Cryptobacteroides sp0004326… ┆ 0.956468 │
│ s__Cryptobacteroides sp9005469… ┆ 0.978856 │
│ s__Cryptobacteroides sp0340892… ┆ 0.978856 │
│ s__Prevotella sp000434975       ┆ 0.960199 │
│ s__Prevotella sp002251295       ┆ 0.962687 │
└─────────────────────────────────┴──────────┘

In [14]:
all_foo = CORE_NAMES.union(SPECIES_ABOVE_95)

In [15]:
xx = []
for name in all_foo:
    is_core = 0
    is_gtdb95 = 0
    if name in CORE_NAMES:
        is_core = 1
    if name in SPECIES_ABOVE_95:
        is_gtdb95 = 1

    xx.append(dict(species_name=name, is_core=is_core, is_gtdb95=is_gtdb95))

xx2_df = pl.DataFrame(xx)

with pl.Config(tbl_rows=-1):
    print(xx2_df.join(by_species, on='species_name', how='inner').sort('freq'))

shape: (19, 4)
┌─────────────────────────────────┬─────────┬───────────┬──────────┐
│ species_name                    ┆ is_core ┆ is_gtdb95 ┆ freq     │
│ ---                             ┆ ---     ┆ ---       ┆ ---      │
│ str                             ┆ i64     ┆ i64       ┆ f64      │
╞═════════════════════════════════╪═════════╪═══════════╪══════════╡
│ s__UBA2868 sp004552595          ┆ 1       ┆ 0         ┆ 0.824316 │
│ s__JAFBIX01 sp021531895         ┆ 1       ┆ 0         ┆ 0.895522 │
│ s__Mogibacterium_A kristiansen… ┆ 1       ┆ 0         ┆ 0.918843 │
│ s__Floccifex porci              ┆ 1       ┆ 0         ┆ 0.924751 │
│ s__Bariatricus sp004560705      ┆ 1       ┆ 0         ┆ 0.939366 │
│ s__Prevotella sp900548195       ┆ 0       ┆ 1         ┆ 0.95056  │
│ s__CAG-170 sp002404795          ┆ 0       ┆ 1         ┆ 0.951182 │
│ s__Colivicinus sp002299675      ┆ 1       ┆ 1         ┆ 0.954913 │
│ s__Ornithospirochaeta sp022785… ┆ 1       ┆ 1         ┆ 0.956157 │
│ s__Cryptobacteroides sp0004326… ┆ 1       ┆ 1         ┆ 0.956468 │
│ s__Prevotella sp000434975       ┆ 1       ┆ 1         ┆ 0.960199 │
│ s__Prevotella sp002251295       ┆ 1       ┆ 1         ┆ 0.962687 │
│ s__Cryptobacteroides sp0004349… ┆ 1       ┆ 1         ┆ 0.968595 │
│ s__Fimisoma sp002320005         ┆ 1       ┆ 1         ┆ 0.973881 │
│ s__Lactobacillus amylovorus     ┆ 1       ┆ 1         ┆ 0.976368 │
│ s__Cryptobacteroides sp9005469… ┆ 1       ┆ 1         ┆ 0.978856 │
│ s__Cryptobacteroides sp0340892… ┆ 1       ┆ 1         ┆ 0.978856 │
│ s__Sodaliphilus sp004557565     ┆ 1       ┆ 1         ┆ 0.990361 │
│ s__Escherichia coli             ┆ 0       ┆ 1         ┆ 0.994403 │
└─────────────────────────────────┴─────────┴───────────┴──────────┘

In [16]:
all_foo.join

AttributeError: 'set' object has no attribute 'join'