In [2]:
# Explore nanopore data

In [3]:
import polars as pl

In [23]:
df = (
    pl.scan_csv('../nanopore-dl/mag+gtdb.x.mf.manysearch.csv')
    .filter(pl.col('intersect_hashes') >= 3)
).collect()

In [24]:
df

shape: (3_792, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GCA_96360 ┆ 98787da90 ┆ null      ┆ 0.001986  ┆ … ┆ 0.690546  ┆ 0.743583  ┆ 5         ┆ 84774    │
│ 6895 s__M ┆ 33ca08f4a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ethanocat ┆ 8e0e553cd ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ell…      ┆ 3be…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_03046 ┆ e97908eff ┆ null      ┆ 0.001804  ┆ … ┆ 0.68119   ┆ 0.740192  ┆ 3         ┆ 84774    │
│ 1285 s__T ┆ db63763b1 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ etragenoc ┆ 79b45d8fc ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ occ…      ┆ 801…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00323 ┆ 11ffa81e7 ┆ null      ┆ 0.000158  ┆ … ┆ 0.64062   ┆ 0.659052  ┆ 4         ┆ 84774    │
│ 8525 s__S ┆ 5a4bb46b3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ taphyloco ┆ 5df6c7051 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ccu…      ┆ cd1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_96360 ┆ 19b86708c ┆ null      ┆ 0.001875  ┆ … ┆ 0.707683  ┆ 0.741551  ┆ 16        ┆ 84774    │
│ 8965 s__A ┆ ce7d31b96 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ lloprevot ┆ c20787494 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ell…      ┆ b5a…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_02137 ┆ b3c5877c5 ┆ null      ┆ 0.000636  ┆ … ┆ 0.67092   ┆ 0.704332  ┆ 6         ┆ 84774    │
│ 6155 s__E ┆ d7a06e754 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ nterococc ┆ 5e3646137 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ us_…      ┆ 6e2…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GCA_03197 ┆ f8b97fc55 ┆ null      ┆ 0.001323  ┆ … ┆ 0.652353  ┆ 0.729345  ┆ 6         ┆ 1335899  │
│ 4155 s__C ┆ 4470ae98e ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hryseobac ┆ 10b908dc3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ter…      ┆ 888…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_04128 ┆ fa31ab556 ┆ null      ┆ 0.001009  ┆ … ┆ 0.640765  ┆ 0.719996  ┆ 6         ┆ 1335899  │
│ 1825 s__P ┆ 29366708d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aenibacil ┆ 378c82936 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ lus…      ┆ 90b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_02278 ┆ 1ecbf1b92 ┆ null      ┆ 0.001986  ┆ … ┆ 0.659472  ┆ 0.743583  ┆ 8         ┆ 1335899  │
│ 2865 s__R ┆ aa9fa8d7f ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ uminococc ┆ 3ce1c01f5 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ oid…      ┆ 84e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_90279 ┆ c883f6d3d ┆ null      ┆ 0.004392  ┆ … ┆ 0.666883  ┆ 0.772232  ┆ 21        ┆ 1335899  │
│ 6915 s__R ┆ 1cf9c6bde ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UG14215   ┆ b95fb3ea1 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp90…     ┆ 6d8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_03663 ┆ 5e8b8552b ┆ null      ┆ 0.002441  ┆ … ┆ 0.656231  ┆ 0.750928  ┆ 8         ┆ 1335899  │
│ 7795 s__C ┆ 124b0ffd2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ lostridiu ┆ d99ae077d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ m s…      ┆ 15f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
OLD_NAMES = [ x.strip() for x in open('../../2025-workflow-core99/inputs.cds/names.list') ]
OLD_NAMES_PLUS = [ x.strip() for x in open('../../2025-workflow-core99/inputs.cds/names-plus.list') ]

In [26]:
OLD_NAMES

['s__Bariatricus sp004560705',
 's__Colivicinus sp002299675',
 's__Cryptobacteroides sp000432655',
 's__Cryptobacteroides sp000434935',
 's__Cryptobacteroides sp034089285',
 's__Cryptobacteroides sp900546925',
 's__Fimisoma sp002320005',
 's__Floccifex porci',
 's__JAFBIX01 sp021531895',
 's__Lactobacillus amylovorus',
 's__Mogibacterium_A kristiansenii',
 's__Ornithospirochaeta sp022785155',
 's__Prevotella sp000434975',
 's__Prevotella sp002251295',
 's__Sodaliphilus sp004557565',
 's__UBA2868 sp004552595']

In [27]:
xx_df = (
    df
    .with_columns(species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " "))
).filter(pl.col('species_name').is_in(OLD_NAMES))

In [28]:
len(OLD_NAMES)

16

In [29]:
xx_df.group_by('match_md5').agg(pl.len())

shape: (3, 2)
┌─────────────────────────────────┬─────┐
│ match_md5                       ┆ len │
│ ---                             ┆ --- │
│ str                             ┆ u32 │
╞═════════════════════════════════╪═════╡
│ 16e675c20c1c0fe49a71975b78237d… ┆ 15  │
│ 8fd570c89a8d877373d6f73b129184… ┆ 15  │
│ b893cc2a564ec11c15aa5a42d4dcd1… ┆ 16  │
└─────────────────────────────────┴─────┘

In [13]:
xx_df = (
    by_species
    .with_columns(species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " "))
).filter((pl.col('species_name').is_in(OLD_NAMES_PLUS)))
with pl.Config(tbl_rows=-1):
    print(xx_df.sort('freq', descending=True))

NameError: name 'by_species' is not defined

In [13]:
len(OLD_NAMES_PLUS)

27

## Ask questions about core species in metagenomes by metagenome

In [14]:
by_acc = (
    df
    .with_columns(
        species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " ")
    )
    .filter(pl.col('species_name').is_in(OLD_NAMES))
    .group_by('match_name').agg(
        n_core=pl.len()
    )
).sort('n_core')

In [15]:
by_acc

shape: (3_210, 2)
┌─────────────┬────────┐
│ match_name  ┆ n_core │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ SRR12795729 ┆ 1      │
│ SRR12795774 ┆ 1      │
│ SRR12795782 ┆ 1      │
│ SRR12795740 ┆ 1      │
│ SRR12795783 ┆ 1      │
│ …           ┆ …      │
│ SRR11183573 ┆ 16     │
│ SRR11126323 ┆ 16     │
│ SRR17241519 ┆ 16     │
│ SRR14812370 ┆ 16     │
│ SRR8960562  ┆ 16     │
└─────────────┴────────┘

In [16]:
low_core_acc = by_acc.filter(pl.col('n_core') < 10)

In [17]:
metadata_df = (
    pl.scan_parquet("/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet")
    .filter(pl.col("acc") != "NP")
    .filter(pl.col("assay_type") == "WGS")
#    .select(["acc", "organism", "bioproject", "mbases", "host", "project_name"]) 
    .collect()
)

In [18]:
low_core_acc = low_core_acc.rename({'match_name': 'acc'})

In [19]:
low_core_acc2 = low_core_acc.join(metadata_df, on='acc', how='left')
low_core_acc2

shape: (57, 68)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ n_core ┆ sample_nam ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---    ┆ e          ┆ me_sam    ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ list[str] ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆        ┆            ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1279572 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 246703483 ┆ "2020-10- ┆ null      ┆ "16396807 │
│ 9          ┆        ┆ 412        ┆           ┆   ┆ 9         ┆ 08T12:26: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279577 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 207750152 ┆ "2020-10- ┆ null      ┆ "16396805 │
│ 4          ┆        ┆ 406        ┆           ┆   ┆ 7         ┆ 08T12:22: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279578 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 290040765 ┆ "2020-10- ┆ null      ┆ "16396824 │
│ 2          ┆        ┆ 424        ┆           ┆   ┆ 6         ┆ 08T12:24: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279574 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 282304744 ┆ "2020-10- ┆ null      ┆ "16396806 │
│ 0          ┆        ┆ 409        ┆           ┆   ┆ 0         ┆ 08T12:31: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279578 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 269320240 ┆ "2020-10- ┆ null      ┆ "16396823 │
│ 3          ┆        ┆ 421        ┆           ┆   ┆ 6         ┆ 08T12:28: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR1804890 ┆ 9      ┆ Control3   ┆ []        ┆ … ┆ 350782295 ┆ "2022-02- ┆ null      ┆ "25980734 │
│ 8          ┆        ┆            ┆           ┆   ┆ 4         ┆ 18T08:18: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804891 ┆ 9      ┆ Berberine5 ┆ []        ┆ … ┆ 545845990 ┆ "2022-02- ┆ null      ┆ "25980742 │
│ 0          ┆        ┆            ┆           ┆   ┆ 8         ┆ 18T08:33: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1112525 ┆ 9      ┆ Ja31/14277 ┆ []        ┆ … ┆ 307295762 ┆ "2020-02- ┆ null      ┆ "11097684 │
│ 0          ┆        ┆            ┆           ┆   ┆           ┆ 20T21:10: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8960541 ┆ 9      ┆ Ja31/29951 ┆ []        ┆ … ┆ 151269173 ┆ "2019-04- ┆ null      ┆ "11097774 │
│            ┆        ┆            ┆           ┆   ┆ 1         ┆ 26T03:21: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1118404 ┆ 9      ┆ Ja31/14277 ┆ []        ┆ … ┆ 342710570 ┆ "2020-02- ┆ null      ┆ "11097684 │
│ 6          ┆        ┆            ┆           ┆   ┆           ┆ 26T03:36: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [20]:
low_core_acc2.group_by('bioproject').agg(
    pl.len()
).sort('len')

shape: (9, 2)
┌─────────────┬─────┐
│ bioproject  ┆ len │
│ ---         ┆ --- │
│ str         ┆ u32 │
╞═════════════╪═════╡
│ PRJNA741980 ┆ 1   │
│ PRJNA629856 ┆ 1   │
│ PRJNA471402 ┆ 1   │
│ PRJNA408025 ┆ 3   │
│ PRJEB31650  ┆ 5   │
│ PRJNA807368 ┆ 7   │
│ PRJNA373834 ┆ 8   │
│ PRJNA526405 ┆ 14  │
│ PRJNA668104 ┆ 17  │
└─────────────┴─────┘

## Explore saturation

In [21]:
sat_df = pl.read_parquet('../../2025-ccbaumler-wort-gathering/wort-sra-signature-saturation.parquet')

In [22]:
sat_df

shape: (5_149_985, 5)
┌─────────────────────────────────┬─────────────┬─────────────┬─────────────┬─────────────────────┐
│ filepath                        ┆ signature   ┆ novel_count ┆ total_count ┆ sequence_saturation │
│ ---                             ┆ ---         ┆ ---         ┆ ---         ┆ ---                 │
│ str                             ┆ str         ┆ i64         ┆ i64         ┆ f64                 │
╞═════════════════════════════════╪═════════════╪═════════════╪═════════════╪═════════════════════╡
│ /group/ctbrowngrp/irber/data/w… ┆ SRR33867156 ┆ 23507       ┆ 397539      ┆ 0.940869            │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR4022268  ┆ 27896       ┆ 308529      ┆ 0.909584            │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR3771976  ┆ 223         ┆ 3174        ┆ 0.929742            │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR11996469 ┆ 20          ┆ 40          ┆ 0.5                 │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR10755277 ┆ 3185        ┆ 26976       ┆ 0.881932            │
│ …                               ┆ …           ┆ …           ┆ …           ┆ …                   │
│ /group/ctbrowngrp/irber/data/w… ┆ SRR9934015  ┆ 57128       ┆ 286525      ┆ 0.800618            │
│ /group/ctbrowngrp/irber/data/w… ┆ SRR7588346  ┆ 67307       ┆ 409191      ┆ 0.835512            │
│ /group/ctbrowngrp/irber/data/w… ┆ SRR10432619 ┆ 88275       ┆ 942001      ┆ 0.90629             │
│ /group/ctbrowngrp/irber/data/w… ┆ SRR4027653  ┆ 800444      ┆ 1241468     ┆ 0.355244            │
│ /group/ctbrowngrp/irber/data/w… ┆ ERR11569305 ┆ 728129      ┆ 5832378     ┆ 0.875157            │
└─────────────────────────────────┴─────────────┴─────────────┴─────────────┴─────────────────────┘

In [23]:
sat_df2 = df.join(sat_df, left_on='match_name', right_on='signature',
                  how='left')

In [24]:
zz = []
for min_sat in (0.25, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9):
    xx_df = sat_df2.filter(pl.col('sequence_saturation') >= min_sat)
    n_acc = xx_df['match_name'].n_unique()
    xx2_df= df.group_by('query_name').agg(
        freq=pl.len() / n_acc
    ).filter(pl.col('freq') >= 0.95)
    zz.append(dict(min=min_sat, num_metag=n_acc, num_core95=len(xx2_df)))
    #print(min_sat, n_acc, len(xx2_df))

zz_df = pl.DataFrame(zz)

In [25]:
zz_df

shape: (8, 3)
┌──────┬───────────┬────────────┐
│ min  ┆ num_metag ┆ num_core95 │
│ ---  ┆ ---       ┆ ---        │
│ f64  ┆ i64       ┆ i64        │
╞══════╪═══════════╪════════════╡
│ 0.25 ┆ 3216      ┆ 17         │
│ 0.3  ┆ 3215      ┆ 17         │
│ 0.4  ┆ 3206      ┆ 18         │
│ 0.5  ┆ 3065      ┆ 38         │
│ 0.6  ┆ 2251      ┆ 269        │
│ 0.7  ┆ 1244      ┆ 737        │
│ 0.8  ┆ 366       ┆ 1724       │
│ 0.9  ┆ 37        ┆ 3116       │
└──────┴───────────┴────────────┘