# Select and characterize 3216 pig gut metagenomes

In [1]:
import polars as pl

In [3]:
# remove shitty entries with shitty metatada
unnannotated_values = [
    "metagenome",
    "gut metagenome",
    "feces metagenome",
    "manure metagenome",
    "bacterium",
    "unidentified",
    "null"
    ]
def remove_unnannotated(df: pl.DataFrame) -> pl.DataFrame:
    return df.filter(~pl.col("organism").is_in(unnannotated_values))


# group by organism and count number of bacteria per SRA 
def pivot_count(df: pl.DataFrame) -> pl.DataFrame:
    return (
        df
        .group_by(["broad_cat", "count"])
        .len()  # count occurrences
        .pivot(
            values="len",
            index="broad_cat",
            on="count"
        )
        .fill_null(0)  # optional: fill missing with 0
    )

# set mapping for "categories of interest" I like human v pig v neither. 
category_map_simple = {
    'human associated': ['human', 'homo', 'sapiens'],
    'pig': ['pig', 'sus', 'scrofa']}

# Function to assign category based on keywords above
def get_broad_cat_simple(organism):
    for cat, keywords in category_map_simple.items():
        if any(keyword.lower() in str(organism).lower() for keyword in keywords):
            return cat
    return 'other'

In [4]:
# get metadata, only compare WGS
metadata_df = (
    pl.scan_parquet("/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet")
    .filter(pl.col("acc") != "NP")
    .filter(pl.col("assay_type") == "WGS")
#    .select(["acc", "organism", "bioproject", "mbases", "host", "project_name"]) 
    .collect()
)
print(f"found metadata records for {len(metadata_df)} WGS metagenome data sets from the SRA")

found metadata records for 703916 WGS metagenome data sets from the SRA

### Create a new dataframe that will provide a 'simpleorg' column: human, pig, other

In [5]:
rename_df = []
for organism in metadata_df['organism'].unique().to_list():
    simpleorg = 'other'
    if organism:
        for kw in ['human', 'homo']:
            if kw in organism.lower():
                simpleorg = 'human'
                break
        for kw in ['pig', 'sus', 'scrofa']:
            if kw in organism.lower():
                simpleorg = 'pig'
                break
    rename_df.append(dict(organism=organism, broad_cat=simpleorg))

rename_df = pl.DataFrame(rename_df)
rename_df['broad_cat'].value_counts().sort(by='count', descending=True)

shape: (3, 2)
┌───────────┬───────┐
│ broad_cat ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ other     ┆ 10208 │
│ human     ┆ 165   │
│ pig       ┆ 36    │
└───────────┴───────┘

### Apply the renaming to the metadata table => metadata2_df

In [6]:
metadata2_df = metadata_df.join(rename_df, on='organism', how='inner', coalesce=True)
assert len(metadata2_df) == len(metadata_df)
metadata2_df

shape: (703_916, 68)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_na ┆ sample_na ┆ acc       ┆ assay_typ ┆ … ┆ run_file_ ┆ run_file_ ┆ primary_s ┆ broad_ca │
│ me        ┆ me_sam    ┆ ---       ┆ e         ┆   ┆ create_da ┆ version   ┆ earch     ┆ t        │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ te        ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ list[str] ┆           ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 27        ┆ []        ┆ SRR285238 ┆ WGS       ┆ … ┆ "2024-04- ┆ null      ┆ "1095378" ┆ human    │
│           ┆           ┆ 69        ┆           ┆   ┆ 02T09:18: ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ CN20      ┆ []        ┆ SRR199011 ┆ WGS       ┆ … ┆ "2022-06- ┆ null      ┆ "29417614 ┆ other    │
│           ┆           ┆ 37        ┆           ┆   ┆ 29T14:47: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ 9419-17   ┆ []        ┆ SRR249624 ┆ WGS       ┆ … ┆ "2023-06- ┆ null      ┆ "35766867 ┆ other    │
│           ┆           ┆ 75        ┆           ┆   ┆ 19T19:32: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ P36       ┆ []        ┆ SRR291613 ┆ WGS       ┆ … ┆ "2024-05- ┆ null      ┆ "1116137" ┆ other    │
│           ┆           ┆ 30        ┆           ┆   ┆ 24T12:56: ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ FS_VIR_SM ┆ []        ┆ SRR266687 ┆ WGS       ┆ … ┆ "2023-11- ┆ null      ┆ "1035769" ┆ other    │
│ J_01      ┆           ┆ 39        ┆           ┆   ┆ 04T14:13: ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SAMEA6854 ┆ ["BARIA_C ┆ ERR417428 ┆ WGS       ┆ … ┆ "2020-06- ┆ null      ┆ "15038733 ┆ human    │
│ 847       ┆ 2_057_A"] ┆ 8         ┆           ┆   ┆ 04T14:30: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ SAMEA5357 ┆ ["MB37_4" ┆ ERR316010 ┆ WGS       ┆ … ┆ "2019-04- ┆ null      ┆ "10960521 ┆ human    │
│ 402       ┆ ]         ┆ 9         ┆           ┆   ┆ 20T10:28: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ SAMEA4799 ┆ ["Evo_Utr ┆ ERR270945 ┆ WGS       ┆ … ┆ "2018-09- ┆ null      ┆ "483292"  ┆ human    │
│ 940       ┆ echt_cin_ ┆ 7         ┆           ┆   ┆ 28T18:44: ┆           ┆           ┆          │
│           ┆ 120_F"]   ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ SAMEA4799 ┆ ["Evo_Mad ┆ ERR270936 ┆ WGS       ┆ … ┆ "2018-09- ┆ null      ┆ "483292"  ┆ human    │
│ 925       ┆ rid_EFQ_3 ┆ 7         ┆           ┆   ┆ 28T19:47: ┆           ┆           ┆          │
│           ┆ 2"]       ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ SAMEA4799 ┆ ["Evo_Mad ┆ ERR270938 ┆ WGS       ┆ … ┆ "2018-09- ┆ null      ┆ "483292"  ┆ human    │
│ 929       ┆ rid_EFQ_3 ┆ 8         ┆           ┆   ┆ 28T16:00: ┆           ┆           ┆          │
│           ┆ 6"]       ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
## Filter metadata table

In [16]:
pig_df = metadata2_df.filter(
    (pl.col('bases').cast(pl.Int64) >= 1e9) &
    (pl.col('broad_cat') == 'pig')
)

In [17]:
pig_df

shape: (5_465, 68)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_na ┆ sample_na ┆ acc       ┆ assay_typ ┆ … ┆ run_file_ ┆ run_file_ ┆ primary_s ┆ broad_ca │
│ me        ┆ me_sam    ┆ ---       ┆ e         ┆   ┆ create_da ┆ version   ┆ earch     ┆ t        │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ te        ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ list[str] ┆           ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ JS_LAK4_S ┆ []        ┆ SRR264431 ┆ WGS       ┆ … ┆ "2023-10- ┆ null      ┆ "37885830 ┆ pig      │
│ 129       ┆           ┆ 77        ┆           ┆   ┆ 19T16:38: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ 215_887_G ┆ []        ┆ SRR259362 ┆ WGS       ┆ … ┆ "2023-09- ┆ null      ┆ "1010706" ┆ pig      │
│ 6_V4      ┆           ┆ 51        ┆           ┆   ┆ 07T04:01: ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Fe24/1420 ┆ []        ┆ SRR111254 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098298 ┆ pig      │
│ 8         ┆           ┆ 86        ┆           ┆   ┆ 20T21:25: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ X12bP419D ┆ []        ┆ SRR260645 ┆ WGS       ┆ … ┆ "2023-09- ┆ null      ┆ "37396117 ┆ pig      │
│ 21C       ┆           ┆ 55        ┆           ┆   ┆ 14T20:20: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ SAMEA3663 ┆ ["BHZ-7B" ┆ ERR113538 ┆ WGS       ┆ … ┆ "2016-01- ┆ null      ┆ "308698"  ┆ pig      │
│ 214       ┆ ]         ┆ 7         ┆           ┆   ┆ 13T01:23: ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ E5-LI-Dis ┆ []        ┆ SRR154100 ┆ WGS       ┆ … ┆ "2021-08- ┆ null      ┆ "20697724 ┆ pig      │
│ t-Lum-1   ┆           ┆ 03        ┆           ┆   ┆ 10T23:11: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Ma8/14306 ┆ []        ┆ SRR896014 ┆ WGS       ┆ … ┆ "2019-04- ┆ null      ┆ "11098459 ┆ pig      │
│           ┆           ┆ 3         ┆           ┆   ┆ 26T03:09: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Fe28/2970 ┆ []        ┆ SRR111254 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098310 ┆ pig      │
│ 5         ┆           ┆ 72        ┆           ┆   ┆ 20T21:17: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Ma9/14208 ┆ []        ┆ SRR111838 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098478 ┆ pig      │
│           ┆           ┆ 01        ┆           ┆   ┆ 26T03:30: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Ma7/14186 ┆ []        ┆ SRR111852 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098444 ┆ pig      │
│           ┆           ┆ 54        ┆           ┆   ┆ 27T08:54: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Check if 3216 is subset...

In [18]:
names_3216_df = (pl.read_csv('../3216.manifest.csv')
                 .with_columns(acc=pl.col('name'))
                 ['acc'].unique().to_frame()
                )
assert len(names_3216_df) == 3216, len(names_3216_df)

In [19]:
assert len(pig_df.join(names_3216_df, on='acc', how='inner')) == 3216

In [15]:
# good!

## Make list of wort sigs

In [20]:
PATH='/group/ctbrowngrp5/wort/wort-sra/sigs/{acc}.sig'

with open('../pig-metag-initial-selection.txt', 'wt') as fp:
    for acc in pig_df['acc']:
        print(PATH.format(acc=acc), file=fp)

## Process results of search

In [60]:
search_df = pl.read_csv('../pig+human.x.pig-metag-initial-selection.csv')

In [61]:
search_df

shape: (9_115, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GCF_00000 ┆ 2edac3821 ┆ SRR111246 ┆ 0.000017  ┆ … ┆ 0.822544  ┆ 0.83875   ┆ 5         ┆ 75348    │
│ 3025.6    ┆ d65091319 ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ pig (Sus  ┆ e98478f22 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ scrof…    ┆ e94…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00000 ┆ 2edac3821 ┆ SRR111248 ┆ 0.000013  ┆ … ┆ 0.816974  ┆ 0.832148  ┆ 3         ┆ 77572    │
│ 3025.6    ┆ d65091319 ┆ 38        ┆           ┆   ┆           ┆           ┆           ┆          │
│ pig (Sus  ┆ e98478f22 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ scrof…    ┆ e94…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00000 ┆ 2edac3821 ┆ SRR896011 ┆ 0.003876  ┆ … ┆ 0.910204  ┆ 0.923571  ┆ 1099      ┆ 198114   │
│ 3025.6    ┆ d65091319 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ pig (Sus  ┆ e98478f22 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ scrof…    ┆ e94…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00000 ┆ 4c128af88 ┆ SRR896011 ┆ 0.000007  ┆ … ┆ 0.806159  ┆ 0.819165  ┆ 4         ┆ 198114   │
│ 1405.40   ┆ 821ccd01a ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ human     ┆ 6f825f484 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ (Homo s…  ┆ 2fe…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00000 ┆ 2edac3821 ┆ SRR111840 ┆ 0.00035   ┆ … ┆ 0.874442  ┆ 0.89335   ┆ 99        ┆ 87133    │
│ 3025.6    ┆ d65091319 ┆ 14        ┆           ┆   ┆           ┆           ┆           ┆          │
│ pig (Sus  ┆ e98478f22 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ scrof…    ┆ e94…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GCF_00000 ┆ 4c128af88 ┆ SRR172416 ┆ 0.000317  ┆ … ┆ 0.851753  ┆ 0.853858  ┆ 129       ┆ 1198246  │
│ 1405.40   ┆ 821ccd01a ┆ 42        ┆           ┆   ┆           ┆           ┆           ┆          │
│ human     ┆ 6f825f484 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ (Homo s…  ┆ 2fe…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00000 ┆ 2edac3821 ┆ SRR103133 ┆ 0.000154  ┆ … ┆ 0.838796  ┆ 0.841835  ┆ 39        ┆ 477589   │
│ 3025.6    ┆ d65091319 ┆ 40        ┆           ┆   ┆           ┆           ┆           ┆          │
│ pig (Sus  ┆ e98478f22 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ scrof…    ┆ e94…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00000 ┆ 4c128af88 ┆ SRR103133 ┆ 0.000022  ┆ … ┆ 0.808664  ┆ 0.810423  ┆ 6         ┆ 477589   │
│ 1405.40   ┆ 821ccd01a ┆ 40        ┆           ┆   ┆           ┆           ┆           ┆          │
│ human     ┆ 6f825f484 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ (Homo s…  ┆ 2fe…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00000 ┆ 2edac3821 ┆ SRR271083 ┆ 0.612989  ┆ … ┆ 0.986125  ┆ 0.99045   ┆ 360500    ┆ 1807236  │
│ 3025.6    ┆ d65091319 ┆ 73        ┆           ┆   ┆           ┆           ┆           ┆          │
│ pig (Sus  ┆ e98478f22 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ scrof…    ┆ e94…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00000 ┆ 4c128af88 ┆ SRR271083 ┆ 0.001105  ┆ … ┆ 0.872471  ┆ 0.875034  ┆ 697       ┆ 1807236  │
│ 1405.40   ┆ 821ccd01a ┆ 73        ┆           ┆   ┆           ┆           ┆           ┆          │
│ human     ┆ 6f825f484 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ (Homo s…  ┆ 2fe…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [62]:
names_3216_df

shape: (3_216, 1)
┌─────────────┐
│ acc         │
│ ---         │
│ str         │
╞═════════════╡
│ ERR1135222  │
│ SRR11183882 │
│ ERR1135393  │
│ ERR3211939  │
│ ERR1135201  │
│ …           │
│ SRR11183931 │
│ ERR8314761  │
│ SRR8960917  │
│ SRR8960944  │
│ SRR11126281 │
└─────────────┘

In [63]:
search_3216_df = search_df.join(names_3216_df, how='semi', left_on='match_name', right_on='acc')

In [66]:
search_3216_df.group_by('query_name').agg(
    pl.col('containment').max()
)

shape: (2, 2)
┌─────────────────────────────────┬─────────────┐
│ query_name                      ┆ containment │
│ ---                             ┆ ---         │
│ str                             ┆ f64         │
╞═════════════════════════════════╪═════════════╡
│ GCF_000001405.40 human (Homo s… ┆ 0.033424    │
│ GCF_000003025.6 pig (Sus scrof… ┆ 0.28903     │
└─────────────────────────────────┴─────────────┘

In [68]:
metadata2_3216_df = metadata2_df.join(names_3216_df, how='semi', left_on='acc', right_on='acc')

In [73]:
trydatecutoff = metadata2_3216_df.select(pl.col('releasedate').max()).item()

In [79]:
metadata2_df.filter(
    (pl.col('releasedate') <= trydatecutoff) &
    (pl.col('organism') == 'pig gut metagenome' ) &
    (pl.col('bases').cast(pl.Int64) >= 1e9)
)

shape: (3_664, 68)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_na ┆ sample_na ┆ acc       ┆ assay_typ ┆ … ┆ run_file_ ┆ run_file_ ┆ primary_s ┆ broad_ca │
│ me        ┆ me_sam    ┆ ---       ┆ e         ┆   ┆ create_da ┆ version   ┆ earch     ┆ t        │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ te        ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ list[str] ┆           ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Fe24/1420 ┆ []        ┆ SRR111254 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098298 ┆ pig      │
│ 8         ┆           ┆ 86        ┆           ┆   ┆ 20T21:25: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ SAMEA3663 ┆ ["BHZ-7B" ┆ ERR113538 ┆ WGS       ┆ … ┆ "2016-01- ┆ null      ┆ "308698"  ┆ pig      │
│ 214       ┆ ]         ┆ 7         ┆           ┆   ┆ 13T01:23: ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Fe24/1420 ┆ []        ┆ SRR111260 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098298 ┆ pig      │
│ 8         ┆           ┆ 80        ┆           ┆   ┆ 20T22:03: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Fe21/2979 ┆ []        ┆ SRR111247 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098250 ┆ pig      │
│ 6         ┆           ┆ 55        ┆           ┆   ┆ 20T20:34: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ PI_5      ┆ []        ┆ SRR127998 ┆ WGS       ┆ … ┆ "2020-10- ┆ null      ┆ "16402095 ┆ pig      │
│           ┆           ┆ 33        ┆           ┆   ┆ 09T06:17: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Fe7/14183 ┆ []        ┆ SRR111249 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11097950 ┆ pig      │
│           ┆           ┆ 12        ┆           ┆   ┆ 20T20:45: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Ma8/14306 ┆ []        ┆ SRR896014 ┆ WGS       ┆ … ┆ "2019-04- ┆ null      ┆ "11098459 ┆ pig      │
│           ┆           ┆ 3         ┆           ┆   ┆ 26T03:09: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Fe28/2970 ┆ []        ┆ SRR111254 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098310 ┆ pig      │
│ 5         ┆           ┆ 72        ┆           ┆   ┆ 20T21:17: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Ma9/14208 ┆ []        ┆ SRR111838 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098478 ┆ pig      │
│           ┆           ┆ 01        ┆           ┆   ┆ 26T03:30: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
│ Ma7/14186 ┆ []        ┆ SRR111852 ┆ WGS       ┆ … ┆ "2020-02- ┆ null      ┆ "11098444 ┆ pig      │
│           ┆           ┆ 54        ┆           ┆   ┆ 27T08:54: ┆           ┆ "         ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00.000Z"  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [55]:
combo_df = search_df.filter(pl.col('query_name').str.contains('Sus scrofa')).group_by('match_name').agg(
    best_cont=pl.col('containment').max()
)

In [58]:
combo_df.filter(pl.col('best_cont') < 0.05)['match_name'].n_unique()

4541

In [59]:
combo_df.join(names_3216_df, left_on='match_name', right_on='acc', how='inner')

shape: (3_162, 2)
┌─────────────┬───────────┐
│ match_name  ┆ best_cont │
│ ---         ┆ ---       │
│ str         ┆ f64       │
╞═════════════╪═══════════╡
│ SRR8960688  ┆ 0.008985  │
│ SRR10209675 ┆ 0.005844  │
│ ERR1135279  ┆ 0.00388   │
│ SRR14369226 ┆ 0.109062  │
│ ERR3211920  ┆ 0.008759  │
│ …           ┆ …         │
│ ERR1135330  ┆ 0.001084  │
│ SRR11184013 ┆ 0.001187  │
│ SRR8960521  ┆ 0.00012   │
│ SRR11183796 ┆ 0.000017  │
│ SRR8960492  ┆ 0.022525  │
└─────────────┴───────────┘