# Utility notebook to translate species-specific genes from old gene names to new

This is something to manually run if you regenerate the prodigal gene calls and/or modify the
cds extraction code in `workflows/mapping.smk`.

BLASTN columns (`--output-fmt 6`)

```
   1.  qseqid      query (gene) sequence id
   2.  sseqid      subject (reference genome) sequence id
   3.  pident      percentage of identical positions
   4.  length      alignment length (sequence overlap)
   5.  mismatch    number of mismatches
   6.  gapopen     number of gap openings
   7.  qstart      start of alignment in query
   8.  qend        end of alignment in query
   9.  sstart      start of alignment in subject
 10.  send        end of alignment in subject
 11.  evalue      expect value
 12.  bitscore    bit score
```

In [1]:
import polars as pl

In [2]:
df = pl.read_csv('../2025-workflow-genes/new/old-x-new.blastn',
                 separator='\t', has_header=False,
                 new_columns=['qseqid', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen', 'qstart', 'qend', 'sstart', 'ssend', 'evalue', 'bitscore'])

In [3]:
df

shape: (741, 12)
┌────────────────┬──────────────────┬────────┬────────┬───┬────────┬───────┬────────────┬──────────┐
│ qseqid         ┆ sseqid           ┆ pident ┆ length ┆ … ┆ sstart ┆ ssend ┆ evalue     ┆ bitscore │
│ ---            ┆ ---              ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---   ┆ ---        ┆ ---      │
│ str            ┆ str              ┆ f64    ┆ i64    ┆   ┆ i64    ┆ i64   ┆ f64        ┆ f64      │
╞════════════════╪══════════════════╪════════╪════════╪═══╪════════╪═══════╪════════════╪══════════╡
│ FGLPJJIK_03110 ┆ AtH2023_SRR71820 ┆ 95.273 ┆ 825    ┆ … ┆ 82     ┆ 905   ┆ 0.0        ┆ 1306.0   │
│                ┆ 46_MAG5_337_5    ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ NLNOELNI_01902 ┆ AtH2023_ERR32118 ┆ 99.207 ┆ 1766   ┆ … ┆ 305    ┆ 2070  ┆ 0.0        ┆ 3184.0   │
│                ┆ 26_MAG3_378_5    ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ MMBDDDLD_00384 ┆ AtH2023_SRR89600 ┆ 95.892 ┆ 998    ┆ … ┆ 1      ┆ 995   ┆ 0.0        ┆ 1611.0   │
│                ┆ 82_MAG05_330_3   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ MMBDDDLD_00384 ┆ AtH2023_SRR59761 ┆ 86.852 ┆ 791    ┆ … ┆ 206    ┆ 993   ┆ 0.0        ┆ 880.0    │
│                ┆ 87_MAG13_87_1    ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ MMBDDDLD_00384 ┆ AtH2023_ERR11354 ┆ 92.346 ┆ 601    ┆ … ┆ 1      ┆ 600   ┆ 0.0        ┆ 854.0    │
│                ┆ 58_MAG11_234_5   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ …              ┆ …                ┆ …      ┆ …      ┆ … ┆ …      ┆ …     ┆ …          ┆ …        │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 85.67  ┆ 321    ┆ … ┆ 10     ┆ 328   ┆ 6.6900e-92 ┆ 335.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 88.446 ┆ 251    ┆ … ┆ 3      ┆ 250   ┆ 2.4400e-81 ┆ 300.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 88.341 ┆ 223    ┆ … ┆ 96     ┆ 317   ┆ 2.4800e-71 ┆ 267.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 91.667 ┆ 156    ┆ … ┆ 182    ┆ 337   ┆ 9.0900e-56 ┆ 215.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 94.286 ┆ 70     ┆ … ┆ 268    ┆ 337   ┆ 5.7100e-23 ┆ 106.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
└────────────────┴──────────────────┴────────┴────────┴───┴────────┴───────┴────────────┴──────────┘

## Get highest-bitscore matches between query and subject sequence IDs

In [4]:
sum_df = (df.sort('bitscore', descending=True).group_by(['qseqid'], maintain_order=True).agg(
        pl.col('sseqid'),
        pl.col('bitscore'),
    ).with_columns(
        sseqid=pl.col('sseqid').list.get(0),
        bitscore=pl.col('bitscore').list.get(0))
    .filter(pl.col('bitscore') > 600)
)

In [5]:
sum_df

shape: (56, 3)
┌────────────────┬─────────────────────────────────┬──────────┐
│ qseqid         ┆ sseqid                          ┆ bitscore │
│ ---            ┆ ---                             ┆ ---      │
│ str            ┆ str                             ┆ f64      │
╞════════════════╪═════════════════════════════════╪══════════╡
│ APOLKBKG_00160 ┆ AtH2023_SRR11489784_MAG01_15_2  ┆ 6006.0   │
│ FCHBMNJF_01297 ┆ AtH2023_SRR14369225_MAG28_11_7… ┆ 5762.0   │
│ BIBFGMOK_00552 ┆ AtH2023_SRR17241510_MAG40_8_10  ┆ 4972.0   │
│ OBGMJDLM_01221 ┆ AtH2023_SRR17241544_MAG06_60_1  ┆ 4723.0   │
│ GFALEAHI_01277 ┆ AtH2023_ERR3211937_MAG3_16_9    ┆ 4320.0   │
│ …              ┆ …                               ┆ …        │
│ IEPMJGAI_00771 ┆ AtH2023_SRR8960673_MAG08_57_36  ┆ 915.0    │
│ LJHBCGLM_01294 ┆ AtH2023_SRR17241641_MAG31_88_1  ┆ 865.0    │
│ NADIOELI_00170 ┆ AtH2023_SRR17241638_MAG02_2_35  ┆ 865.0    │
│ AKLOHKAG_01416 ┆ AtH2023_SRR8960301_MAG10_123_3… ┆ 769.0    │
│ OIGHMFGK_00345 ┆ AtH2023_SRR8960669_MAG08_76_1   ┆ 743.0    │
└────────────────┴─────────────────────────────────┴──────────┘

In [6]:
species_genes_df = pl.read_csv('../2025-workflow-genes/species-genes.csv')
species_genes_df

shape: (387, 5)
┌──────┬────────┬─────────────────────────────┬────────────────┬───────────────────────────────────┐
│ good ┆ anchor ┆ species                     ┆ gene_name      ┆ description                       │
│ ---  ┆ ---    ┆ ---                         ┆ ---            ┆ ---                               │
│ i64  ┆ i64    ┆ str                         ┆ str            ┆ str                               │
╞══════╪════════╪═════════════════════════════╪════════════════╪═══════════════════════════════════╡
│ 1    ┆ 1      ┆ s__Phascolarctobacterium_A  ┆ CNENGHLA_01260 ┆ BLAST match to hydrogenase lar…   │
│      ┆        ┆ suc…                        ┆                ┆                                   │
│ 1    ┆ 0      ┆ s__Phascolarctobacterium_A  ┆ EHOAPHDI_01174 ┆ BLAST match to protein phospha…   │
│      ┆        ┆ suc…                        ┆                ┆                                   │
│ 1    ┆ 0      ┆ s__Phascolarctobacterium_A  ┆ CNENGHLA_00658 ┆ BLAST match to 4-hydroxy-3-met…   │
│      ┆        ┆ suc…                        ┆                ┆                                   │
│ 1    ┆ 0      ┆ s__Phascolarctobacterium_A  ┆ IFIBFMPA_00800 ┆ BLAST match to  2-isopropylmal…   │
│      ┆        ┆ suc…                        ┆                ┆                                   │
│ 1    ┆ 0      ┆ s__Lactobacillus amylovorus ┆ BBOFCOCJ_01349 ┆ BLAST match to peptidase T [La…   │
│ …    ┆ …      ┆ …                           ┆ …              ┆ …                                 │
│ 0    ┆ 0      ┆ s__Cryptobacteroides        ┆ ADCODNMF_01281 ┆ (not reviewed)                    │
│      ┆        ┆ sp0004349…                  ┆                ┆                                   │
│ 0    ┆ 0      ┆ s__Cryptobacteroides        ┆ EIGGHFPC_02121 ┆ (not reviewed)                    │
│      ┆        ┆ sp0004349…                  ┆                ┆                                   │
│ 0    ┆ 0      ┆ s__Cryptobacteroides        ┆ DOLCGLJK_00897 ┆ (not reviewed)                    │
│      ┆        ┆ sp0004349…                  ┆                ┆                                   │
│ 1    ┆ 1      ┆ s__Floccifex porci          ┆ IIAENJBH_00799 ┆ anaerobic ribonucleoside-triph…   │
│ 1    ┆ 1      ┆ s__Fimisoma sp002320005     ┆ JBNOCHBL_00669 ┆ PEP/pyruvate-binding domain-co…   │
└──────┴────────┴─────────────────────────────┴────────────────┴───────────────────────────────────┘

In [7]:
new_genes_df = species_genes_df.join(sum_df.drop('bitscore'),
                                     left_on='gene_name',
                                     right_on='qseqid', how='inner')

In [8]:
new_genes_df  = new_genes_df.drop('gene_name').rename({'sseqid': 'gene_name'})

In [9]:
new_genes_df.write_csv('../inputs.genes/TRY-species-genes.csv')

# rename to / concat with 'species-genes.csv'.

In [10]:
new_genes_df

shape: (59, 5)
┌──────┬────────┬───────────────────────────┬───────────────────────────┬──────────────────────────┐
│ good ┆ anchor ┆ species                   ┆ description               ┆ gene_name                │
│ ---  ┆ ---    ┆ ---                       ┆ ---                       ┆ ---                      │
│ i64  ┆ i64    ┆ str                       ┆ str                       ┆ str                      │
╞══════╪════════╪═══════════════════════════╪═══════════════════════════╪══════════════════════════╡
│ 1    ┆ 0      ┆ s__Lactobacillus          ┆ BLAST match to peptidase  ┆ AtH2023_SRR11125358_MAG1 │
│      ┆        ┆ amylovorus                ┆ T [La…                    ┆ _217_2…                  │
│ 1    ┆ 0      ┆ s__Lactobacillus          ┆ BLAST match to            ┆ AtH2023_SRR17241544_MAG0 │
│      ┆        ┆ amylovorus                ┆ calcium-translo…          ┆ 6_60_1                   │
│ 1    ┆ 1      ┆ s__Lactobacillus          ┆ BLAST match to            ┆ AtH2023_SRR8960431_MAG03 │
│      ┆        ┆ amylovorus                ┆ LD-transpeptida…          ┆ _43_3                    │
│ 1    ┆ 0      ┆ s__Bariatricus            ┆ BLAST match to competence ┆ AtH2023_SRR17241619_MAG3 │
│      ┆        ┆ sp004560705               ┆ prot…                     ┆ 7_18_8                   │
│ 1    ┆ 0      ┆ s__Mogibacterium_A        ┆ BLAST match to isolate    ┆ AtH2023_SRR17241623_MAG0 │
│      ┆        ┆ kristiansen…              ┆ genome                    ┆ 6_3_11                   │
│ …    ┆ …      ┆ …                         ┆ …                         ┆ …                        │
│ 1    ┆ 1      ┆ s__Cryptobacteroides      ┆ hypothetical protein      ┆ AtH2023_SRR8960403_MAG06 │
│      ┆        ┆ sp0004349…                ┆ [Bacteroi…                ┆ _120_8                   │
│ 1    ┆ 0      ┆ s__Cryptobacteroides      ┆ putative uncharacterized  ┆ AtH2023_SRR17241635_MAG1 │
│      ┆        ┆ sp0004349…                ┆ prote…                    ┆ 2_71_7                   │
│ 1    ┆ 0      ┆ s__Cryptobacteroides      ┆ ATP-binding protein       ┆ AtH2023_SRR14369225_MAG2 │
│      ┆        ┆ sp0004349…                ┆ [Bacteroid…               ┆ 8_11_7…                  │
│ 1    ┆ 1      ┆ s__Floccifex porci        ┆ anaerobic                 ┆ AtH2023_SRR11126230_MAG2 │
│      ┆        ┆                           ┆ ribonucleoside-triph…     ┆ _46_3                    │
│ 1    ┆ 1      ┆ s__Fimisoma sp002320005   ┆ PEP/pyruvate-binding      ┆ AtH2023_SRR8960631_MAG16 │
│      ┆        ┆                           ┆ domain-co…                ┆ _82_35                   │
└──────┴────────┴───────────────────────────┴───────────────────────────┴──────────────────────────┘