# Utility notebook to translate species-specific genes from old gene names to new

This is something to manually run if you regenerate the prodigal gene calls and/or modify the
cds extraction code in `workflows/mapping.smk`.

See the directory '../2025-workflow-genes'.

BLASTN columns (`--output-fmt 6`)

```
   1.  qseqid      query (gene) sequence id
   2.  sseqid      subject (reference genome) sequence id
   3.  pident      percentage of identical positions
   4.  length      alignment length (sequence overlap)
   5.  mismatch    number of mismatches
   6.  gapopen     number of gap openings
   7.  qstart      start of alignment in query
   8.  qend        end of alignment in query
   9.  sstart      start of alignment in subject
 10.  send        end of alignment in subject
 11.  evalue      expect value
 12.  bitscore    bit score
```

In [1]:
import polars as pl

In [2]:
df = pl.read_csv('../2025-workflow-genes/new/old-x-new.blastn',
                 separator='\t', has_header=False,
                 new_columns=['qseqid', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen', 'qstart', 'qend', 'sstart', 'ssend', 'evalue', 'bitscore'])

In [3]:
df

shape: (888, 12)
┌────────────────┬──────────────────┬────────┬────────┬───┬────────┬───────┬────────────┬──────────┐
│ qseqid         ┆ sseqid           ┆ pident ┆ length ┆ … ┆ sstart ┆ ssend ┆ evalue     ┆ bitscore │
│ ---            ┆ ---              ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---   ┆ ---        ┆ ---      │
│ str            ┆ str              ┆ f64    ┆ i64    ┆   ┆ i64    ┆ i64   ┆ f64        ┆ f64      │
╞════════════════╪══════════════════╪════════╪════════╪═══╪════════╪═══════╪════════════╪══════════╡
│ FGLPJJIK_03110 ┆ CAKTWJ010000034. ┆ 95.515 ┆ 825    ┆ … ┆ 1      ┆ 824   ┆ 0.0        ┆ 1317.0   │
│                ┆ 1_10             ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ FGLPJJIK_03110 ┆ AtH2023_SRR71820 ┆ 95.273 ┆ 825    ┆ … ┆ 82     ┆ 905   ┆ 0.0        ┆ 1306.0   │
│                ┆ 46_MAG5_337_5    ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ FGLPJJIK_03110 ┆ CAVEFX010000253. ┆ 98.425 ┆ 127    ┆ … ┆ 1146   ┆ 1272  ┆ 2.4100e-58 ┆ 224.0    │
│                ┆ 1_4              ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ NLNOELNI_01902 ┆ JAXEUL010000285. ┆ 100.0  ┆ 2043   ┆ … ┆ 1      ┆ 2043  ┆ 0.0        ┆ 3773.0   │
│                ┆ 1_8              ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ NLNOELNI_01902 ┆ CAVEFX010000131. ┆ 97.365 ┆ 1784   ┆ … ┆ 305    ┆ 2088  ┆ 0.0        ┆ 3018.0   │
│                ┆ 1_8              ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ …              ┆ …                ┆ …      ┆ …      ┆ … ┆ …      ┆ …     ┆ …          ┆ …        │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 85.67  ┆ 321    ┆ … ┆ 10     ┆ 328   ┆ 8.6900e-92 ┆ 335.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 88.446 ┆ 251    ┆ … ┆ 3      ┆ 250   ┆ 3.1700e-81 ┆ 300.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 88.341 ┆ 223    ┆ … ┆ 96     ┆ 317   ┆ 3.2200e-71 ┆ 267.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 91.667 ┆ 156    ┆ … ┆ 182    ┆ 337   ┆ 1.1800e-55 ┆ 215.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
│ AKLOHKAG_01416 ┆ AtH2023_SRR17241 ┆ 94.286 ┆ 70     ┆ … ┆ 268    ┆ 337   ┆ 7.4200e-23 ┆ 106.0    │
│                ┆ 623_MAG06_3_11   ┆        ┆        ┆   ┆        ┆       ┆            ┆          │
└────────────────┴──────────────────┴────────┴────────┴───┴────────┴───────┴────────────┴──────────┘

## Get highest-bitscore matches between query and subject sequence IDs

In [13]:
sum_df = (
    df
    .sort('bitscore', descending=True).group_by(['qseqid'], maintain_order=True).agg(
        pl.col('sseqid'),
        pl.col('bitscore'),
        pl.col('evalue'),
    ).with_columns(
        sseqid=pl.col('sseqid').list.get(0),
        bitscore=pl.col('bitscore').list.get(0),
        evalue=pl.col('evalue').list.get(0)
    )
    .filter(pl.col('bitscore') > 600)
)

In [15]:
sum_df.style

GT(_tbl_data=shape: (59, 4)
┌────────────────┬────────────────────────────────┬──────────┬────────┐
│ qseqid         ┆ sseqid                         ┆ bitscore ┆ evalue │
│ ---            ┆ ---                            ┆ ---      ┆ ---    │
│ str            ┆ str                            ┆ f64      ┆ f64    │
╞════════════════╪════════════════════════════════╪══════════╪════════╡
│ FCHBMNJF_01297 ┆ JAXXYX010000113.1_2            ┆ 6649.0   ┆ 0.0    │
│ APOLKBKG_00160 ┆ AtH2023_SRR11489784_MAG01_15_2 ┆ 6006.0   ┆ 0.0    │
│ FCPPOLBJ_01182 ┆ JAJXSD010000002.1_732          ┆ 5347.0   ┆ 0.0    │
│ BIBFGMOK_00552 ┆ JAXUOS010000140.1_2            ┆ 5158.0   ┆ 0.0    │
│ DIHHAJIK_01286 ┆ CAMEXL010000071.1_6            ┆ 4992.0   ┆ 0.0    │
│ …              ┆ …                              ┆ …        ┆ …      │
│ IGEONAAO_00273 ┆ AtH2023_SRR14369270_MAG08_9_3  ┆ 920.0    ┆ 0.0    │
│ IEPMJGAI_00771 ┆ AtH2023_SRR8960673_MAG08_57_36 ┆ 915.0    ┆ 0.0    │
│ LJHBCGLM_01294 ┆ AtH2023_SRR17241641_MAG31_88_1 ┆ 865.0    ┆ 0.0    │
│ NADIOELI_00170 ┆ AtH2023_SRR17241638_MAG02_2_35 ┆ 865.0    ┆ 0.0    │
│ OIGHMFGK_00345 ┆ AtH2023_SRR8960669_MAG08_76_1  ┆ 743.0    ┆ 0.0    │
└────────────────┴────────────────────────────────┴──────────┴────────┘, _body=<great_tables._gt_data.Body object at 0x70a3828f2ed0>, _boxhead=Boxhead([ColInfo(var='qseqid', type=<ColInfoTypeEnum.default: 1>, column_label='qseqid', column_align='left', column_width=None), ColInfo(var='sseqid', type=<ColInfoTypeEnum.default: 1>, column_label='sseqid', column_align='left', column_width=None), ColInfo(var='bitscore', type=<ColInfoTypeEnum.default: 1>, column_label='bitscore', column_align='right', column_width=None), ColInfo(var='evalue', type=<ColInfoTypeEnum.default: 1>, column_label='evalue', column_align='right', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x70a3d420bbf0>, _spanners=Spanners([]), _heading=Heading(title=None, subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x70a382862060>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x70a382863e90>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x70a3c4313680>, _formats=[], _substitutions=[], _col_merge=[], _transforms=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_indent_length=OptionsInfo(scss=True, category='stub', type='px', value='5px'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), summary_row_padding=OptionsInfo(scss=True, category='summary_row', type='px', value='8px'), summary_row_padding_horizontal=OptionsInfo(scss=True, category='summary_row', type='px', value='5px'), summary_row_background_color=OptionsInfo(scss=True, category='summary_row', type='value', value=None), summary_row_text_transform=OptionsInfo(scss=True, category='summary_row', type='value', value='inherit'), summary_row_border_style=OptionsInfo(scss=True, category='summary_row', type='value', value='solid'), summary_row_border_width=OptionsInfo(scss=True, category='summary_row', type='px', value='2px'), summary_row_border_color=OptionsInfo(scss=True, category='summary_row', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), footnotes_marks=OptionsInfo(scss=False, category='footnotes', type='values', value='numbers'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False), ihtml_active=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_pagination=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_pagination_info=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_sorting=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_search=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_filters=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_resizers=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_highlight=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_compact_mode=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_text_wrapping=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_page_size_select=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_page_size_default=OptionsInfo(scss=False, category='ihtml', type='value', value=10), ihtml_page_size_values=OptionsInfo(scss=False, category='ihtml', type='values', value=[10, 25, 50, 100]), ihtml_pagination_type=OptionsInfo(scss=False, category='ihtml', type='value', value='numbers'), ihtml_height=OptionsInfo(scss=False, category='ihtml', type='value', value='auto'), ihtml_selection_mode=OptionsInfo(scss=False, category='ihtml', type='value', value=None)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

## Read in old species-genes list

In [16]:
species_genes_df = pl.read_csv('../2025-workflow-genes/species-genes.csv')
species_genes_df

shape: (387, 5)
┌──────┬────────┬─────────────────────────────┬────────────────┬───────────────────────────────────┐
│ good ┆ anchor ┆ species                     ┆ gene_name      ┆ description                       │
│ ---  ┆ ---    ┆ ---                         ┆ ---            ┆ ---                               │
│ i64  ┆ i64    ┆ str                         ┆ str            ┆ str                               │
╞══════╪════════╪═════════════════════════════╪════════════════╪═══════════════════════════════════╡
│ 1    ┆ 1      ┆ s__Phascolarctobacterium_A  ┆ CNENGHLA_01260 ┆ BLAST match to hydrogenase lar…   │
│      ┆        ┆ suc…                        ┆                ┆                                   │
│ 1    ┆ 0      ┆ s__Phascolarctobacterium_A  ┆ EHOAPHDI_01174 ┆ BLAST match to protein phospha…   │
│      ┆        ┆ suc…                        ┆                ┆                                   │
│ 1    ┆ 0      ┆ s__Phascolarctobacterium_A  ┆ CNENGHLA_00658 ┆ BLAST match to 4-hydroxy-3-met…   │
│      ┆        ┆ suc…                        ┆                ┆                                   │
│ 1    ┆ 0      ┆ s__Phascolarctobacterium_A  ┆ IFIBFMPA_00800 ┆ BLAST match to  2-isopropylmal…   │
│      ┆        ┆ suc…                        ┆                ┆                                   │
│ 1    ┆ 0      ┆ s__Lactobacillus amylovorus ┆ BBOFCOCJ_01349 ┆ BLAST match to peptidase T [La…   │
│ …    ┆ …      ┆ …                           ┆ …              ┆ …                                 │
│ 0    ┆ 0      ┆ s__Cryptobacteroides        ┆ ADCODNMF_01281 ┆ (not reviewed)                    │
│      ┆        ┆ sp0004349…                  ┆                ┆                                   │
│ 0    ┆ 0      ┆ s__Cryptobacteroides        ┆ EIGGHFPC_02121 ┆ (not reviewed)                    │
│      ┆        ┆ sp0004349…                  ┆                ┆                                   │
│ 0    ┆ 0      ┆ s__Cryptobacteroides        ┆ DOLCGLJK_00897 ┆ (not reviewed)                    │
│      ┆        ┆ sp0004349…                  ┆                ┆                                   │
│ 1    ┆ 1      ┆ s__Floccifex porci          ┆ IIAENJBH_00799 ┆ anaerobic ribonucleoside-triph…   │
│ 1    ┆ 1      ┆ s__Fimisoma sp002320005     ┆ JBNOCHBL_00669 ┆ PEP/pyruvate-binding domain-co…   │
└──────┴────────┴─────────────────────────────┴────────────────┴───────────────────────────────────┘

## Join with new names

In [17]:
new_genes_df = species_genes_df.join(sum_df.drop('bitscore'),
                                     left_on='gene_name',
                                     right_on='qseqid', how='inner')

## Adopt new names

In [18]:
new_genes_df  = new_genes_df.drop('gene_name').rename({'sseqid': 'gene_name'})

## Save to temporary file for manual review/curation

In [21]:
new_genes_df.write_csv('../inputs.genes/TRY-species-genes.csv')

# rename to / concat with 'species-genes.csv'.

In [22]:
new_genes_df

shape: (62, 6)
┌──────┬────────┬────────────────────────┬────────────────────────┬───────────────────────┬────────┐
│ good ┆ anchor ┆ species                ┆ description            ┆ gene_name             ┆ evalue │
│ ---  ┆ ---    ┆ ---                    ┆ ---                    ┆ ---                   ┆ ---    │
│ i64  ┆ i64    ┆ str                    ┆ str                    ┆ str                   ┆ f64    │
╞══════╪════════╪════════════════════════╪════════════════════════╪═══════════════════════╪════════╡
│ 1    ┆ 0      ┆ s__Lactobacillus       ┆ BLAST match to         ┆ DOGE01000123.1_5      ┆ 0.0    │
│      ┆        ┆ amylovorus             ┆ peptidase T [La…       ┆                       ┆        │
│ 1    ┆ 0      ┆ s__Lactobacillus       ┆ BLAST match to         ┆ SFOA01000018.1_8      ┆ 0.0    │
│      ┆        ┆ amylovorus             ┆ calcium-translo…       ┆                       ┆        │
│ 1    ┆ 1      ┆ s__Lactobacillus       ┆ BLAST match to         ┆ NZ_JAXGLM010000002.1_ ┆ 0.0    │
│      ┆        ┆ amylovorus             ┆ LD-transpeptida…       ┆ 696                   ┆        │
│ 1    ┆ 1      ┆ s__Bariatricus         ┆ BLAST match to BREX    ┆ JAXFGB010000093.1_6   ┆ 0.0    │
│      ┆        ┆ sp004560705            ┆ system Lon…            ┆                       ┆        │
│ 1    ┆ 0      ┆ s__Bariatricus         ┆ BLAST match to         ┆ AtH2023_SRR17241619_M ┆ 0.0    │
│      ┆        ┆ sp004560705            ┆ competence prot…       ┆ AG37_18_8             ┆        │
│ …    ┆ …      ┆ …                      ┆ …                      ┆ …                     ┆ …      │
│ 1    ┆ 1      ┆ s__Cryptobacteroides   ┆ hypothetical protein   ┆ AtH2023_SRR8960403_MA ┆ 0.0    │
│      ┆        ┆ sp0004349…             ┆ [Bacteroi…             ┆ G06_120_8             ┆        │
│ 1    ┆ 0      ┆ s__Cryptobacteroides   ┆ putative               ┆ DAIUGV010000255.1_1   ┆ 0.0    │
│      ┆        ┆ sp0004349…             ┆ uncharacterized prote… ┆                       ┆        │
│ 1    ┆ 0      ┆ s__Cryptobacteroides   ┆ ATP-binding protein    ┆ JAXXYX010000113.1_2   ┆ 0.0    │
│      ┆        ┆ sp0004349…             ┆ [Bacteroid…            ┆                       ┆        │
│ 1    ┆ 1      ┆ s__Floccifex porci     ┆ anaerobic              ┆ AtH2023_SRR11126230_M ┆ 0.0    │
│      ┆        ┆                        ┆ ribonucleoside-triph…  ┆ AG2_46_3              ┆        │
│ 1    ┆ 1      ┆ s__Fimisoma            ┆ PEP/pyruvate-binding   ┆ AtH2023_SRR8960631_MA ┆ 0.0    │
│      ┆        ┆ sp002320005            ┆ domain-co…             ┆ G16_82_35             ┆        │
└──────┴────────┴────────────────────────┴────────────────────────┴───────────────────────┴────────┘